
/* this file is generated by com.netspective.sparx.xaf.form.Dialog.getSubclassedDialogContextCode(), do not modify (you can extend it, though) */

package dialog.context.main;

import com.netspective.sparx.xaf.form.*;

public class PrescriptionEntryContext extends DialogContext
{
	public boolean isPhysicianNameValueSet() { return hasValue("physician_name"); }
	public boolean isPhysicianNameFlagSet(long flag) { return flagIsSet("physician_name", flag); }
	public void setPhysicianNameFlag(long flag) { setFlag("physician_name", flag); }
	public void clearPhysicianNameFlag(long flag) { clearFlag("physician_name", flag); }
	public String getPhysicianNameRequestParam() { return request.getParameter("_dc.physician_name"); }
	public DialogField getPhysicianNameField() { return getField("physician_name"); }
	public DialogContext.DialogFieldState getPhysicianNameFieldState() { return getFieldState("physician_name"); }
	public void addPhysicianNameErrorMsg(String msg) { addErrorMessage("physician_name", msg); }
	public String getPhysicianName() { return getValue("physician_name"); }
	public String getPhysicianName(String defaultValue) { return getValue("physician_name", defaultValue); }
	public String getPhysicianNameOrBlank() { return getValue("physician_name", ""); }
	public void setPhysicianName(String value) { setValue("physician_name", value); }

	public boolean isDeaNumberValueSet() { return hasValue("dea_number"); }
	public boolean isDeaNumberFlagSet(long flag) { return flagIsSet("dea_number", flag); }
	public void setDeaNumberFlag(long flag) { setFlag("dea_number", flag); }
	public void clearDeaNumberFlag(long flag) { clearFlag("dea_number", flag); }
	public String getDeaNumberRequestParam() { return request.getParameter("_dc.dea_number"); }
	public DialogField getDeaNumberField() { return getField("dea_number"); }
	public DialogContext.DialogFieldState getDeaNumberFieldState() { return getFieldState("dea_number"); }
	public void addDeaNumberErrorMsg(String msg) { addErrorMessage("dea_number", msg); }
	public String getDeaNumber() { return getValue("dea_number"); }
	public String getDeaNumber(String defaultValue) { return getValue("dea_number", defaultValue); }
	public String getDeaNumberOrBlank() { return getValue("dea_number", ""); }
	public void setDeaNumber(String value) { setValue("dea_number", value); }

	public boolean isPiValueSet() { return hasValue("pi"); }
	public boolean isPiFlagSet(long flag) { return flagIsSet("pi", flag); }
	public void setPiFlag(long flag) { setFlag("pi", flag); }
	public void clearPiFlag(long flag) { clearFlag("pi", flag); }
	public String getPiRequestParam() { return request.getParameter("_dc.pi"); }
	public DialogField getPiField() { return getField("pi"); }
	public DialogContext.DialogFieldState getPiFieldState() { return getFieldState("pi"); }
	public void addPiErrorMsg(String msg) { addErrorMessage("pi", msg); }
	public String getPi() { return getValue("pi"); }
	public String getPi(String defaultValue) { return getValue("pi", defaultValue); }
	public String getPiOrBlank() { return getValue("pi", ""); }
	public void setPi(String value) { setValue("pi", value); }

	public boolean isNameFirstValueSet() { return hasValue("name_first"); }
	public boolean isNameFirstFlagSet(long flag) { return flagIsSet("name_first", flag); }
	public void setNameFirstFlag(long flag) { setFlag("name_first", flag); }
	public void clearNameFirstFlag(long flag) { clearFlag("name_first", flag); }
	public String getNameFirstRequestParam() { return request.getParameter("_dc.name_first"); }
	public DialogField getNameFirstField() { return getField("name_first"); }
	public DialogContext.DialogFieldState getNameFirstFieldState() { return getFieldState("name_first"); }
	public void addNameFirstErrorMsg(String msg) { addErrorMessage("name_first", msg); }
	public String getNameFirst() { return getValue("name_first"); }
	public String getNameFirst(String defaultValue) { return getValue("name_first", defaultValue); }
	public String getNameFirstOrBlank() { return getValue("name_first", ""); }
	public void setNameFirst(String value) { setValue("name_first", value); }

	public boolean isNameLastValueSet() { return hasValue("name_last"); }
	public boolean isNameLastFlagSet(long flag) { return flagIsSet("name_last", flag); }
	public void setNameLastFlag(long flag) { setFlag("name_last", flag); }
	public void clearNameLastFlag(long flag) { clearFlag("name_last", flag); }
	public String getNameLastRequestParam() { return request.getParameter("_dc.name_last"); }
	public DialogField getNameLastField() { return getField("name_last"); }
	public DialogContext.DialogFieldState getNameLastFieldState() { return getFieldState("name_last"); }
	public void addNameLastErrorMsg(String msg) { addErrorMessage("name_last", msg); }
	public String getNameLast() { return getValue("name_last"); }
	public String getNameLast(String defaultValue) { return getValue("name_last", defaultValue); }
	public String getNameLastOrBlank() { return getValue("name_last", ""); }
	public void setNameLast(String value) { setValue("name_last", value); }

	public boolean isPersonIdValueSet() { return hasValue("person_id"); }
	public boolean isPersonIdFlagSet(long flag) { return flagIsSet("person_id", flag); }
	public void setPersonIdFlag(long flag) { setFlag("person_id", flag); }
	public void clearPersonIdFlag(long flag) { clearFlag("person_id", flag); }
	public String getPersonIdRequestParam() { return request.getParameter("_dc.person_id"); }
	public DialogField getPersonIdField() { return getField("person_id"); }
	public DialogContext.DialogFieldState getPersonIdFieldState() { return getFieldState("person_id"); }
	public void addPersonIdErrorMsg(String msg) { addErrorMessage("person_id", msg); }
	public String getPersonId() { return getValue("person_id"); }
	public String getPersonId(String defaultValue) { return getValue("person_id", defaultValue); }
	public String getPersonIdOrBlank() { return getValue("person_id", ""); }
	public void setPersonId(String value) { setValue("person_id", value); }

	public boolean isSsnValueSet() { return hasValue("ssn"); }
	public boolean isSsnFlagSet(long flag) { return flagIsSet("ssn", flag); }
	public void setSsnFlag(long flag) { setFlag("ssn", flag); }
	public void clearSsnFlag(long flag) { clearFlag("ssn", flag); }
	public String getSsnRequestParam() { return request.getParameter("_dc.ssn"); }
	public DialogField getSsnField() { return getField("ssn"); }
	public DialogContext.DialogFieldState getSsnFieldState() { return getFieldState("ssn"); }
	public void addSsnErrorMsg(String msg) { addErrorMessage("ssn", msg); }
	public String getSsn() { return getValue("ssn"); }
	public String getSsn(String defaultValue) { return getValue("ssn", defaultValue); }
	public String getSsnOrBlank() { return getValue("ssn", ""); }
	public void setSsn(String value) { setValue("ssn", value); }

	public boolean isPi2ValueSet() { return hasValue("pi2"); }
	public boolean isPi2FlagSet(long flag) { return flagIsSet("pi2", flag); }
	public void setPi2Flag(long flag) { setFlag("pi2", flag); }
	public void clearPi2Flag(long flag) { clearFlag("pi2", flag); }
	public String getPi2RequestParam() { return request.getParameter("_dc.pi2"); }
	public DialogField getPi2Field() { return getField("pi2"); }
	public DialogContext.DialogFieldState getPi2FieldState() { return getFieldState("pi2"); }
	public void addPi2ErrorMsg(String msg) { addErrorMessage("pi2", msg); }
	public String getPi2() { return getValue("pi2"); }
	public String getPi2(String defaultValue) { return getValue("pi2", defaultValue); }
	public String getPi2OrBlank() { return getValue("pi2", ""); }
	public void setPi2(String value) { setValue("pi2", value); }

	public boolean isDrugValueSet() { return hasValue("drug"); }
	public boolean isDrugFlagSet(long flag) { return flagIsSet("drug", flag); }
	public void setDrugFlag(long flag) { setFlag("drug", flag); }
	public void clearDrugFlag(long flag) { clearFlag("drug", flag); }
	public String getDrugRequestParam() { return request.getParameter("_dc.drug"); }
	public DialogField getDrugField() { return getField("drug"); }
	public DialogContext.DialogFieldState getDrugFieldState() { return getFieldState("drug"); }
	public void addDrugErrorMsg(String msg) { addErrorMessage("drug", msg); }
	public String getDrug() { return getValue("drug"); }
	public String getDrug(String defaultValue) { return getValue("drug", defaultValue); }
	public int getDrugInt() { String s = getValue("drug"); return s == null ? -1 : Integer.parseInt(s); }
	public int getDrugInt(int defaultValue) { String s = getValue("drug"); return s == null ? defaultValue : Integer.parseInt(s); }
	public void setDrug(String value) { setValue("drug", value); }
	public void setDrug(int value) { setValue("drug", Integer.toString(value)); }

	public boolean isDosageValueSet() { return hasValue("dosage"); }
	public boolean isDosageFlagSet(long flag) { return flagIsSet("dosage", flag); }
	public void setDosageFlag(long flag) { setFlag("dosage", flag); }
	public void clearDosageFlag(long flag) { clearFlag("dosage", flag); }
	public String getDosageRequestParam() { return request.getParameter("_dc.dosage"); }
	public DialogField getDosageField() { return getField("dosage"); }
	public DialogContext.DialogFieldState getDosageFieldState() { return getFieldState("dosage"); }
	public void addDosageErrorMsg(String msg) { addErrorMessage("dosage", msg); }
	public String getDosage() { return getValue("dosage"); }
	public String getDosage(String defaultValue) { return getValue("dosage", defaultValue); }
	public int getDosageInt() { String s = getValue("dosage"); return s == null ? -1 : Integer.parseInt(s); }
	public int getDosageInt(int defaultValue) { String s = getValue("dosage"); return s == null ? defaultValue : Integer.parseInt(s); }
	public void setDosage(String value) { setValue("dosage", value); }
	public void setDosage(int value) { setValue("dosage", Integer.toString(value)); }

	public boolean isQuantityValueSet() { return hasValue("quantity"); }
	public boolean isQuantityFlagSet(long flag) { return flagIsSet("quantity", flag); }
	public void setQuantityFlag(long flag) { setFlag("quantity", flag); }
	public void clearQuantityFlag(long flag) { clearFlag("quantity", flag); }
	public String getQuantityRequestParam() { return request.getParameter("_dc.quantity"); }
	public DialogField getQuantityField() { return getField("quantity"); }
	public DialogContext.DialogFieldState getQuantityFieldState() { return getFieldState("quantity"); }
	public void addQuantityErrorMsg(String msg) { addErrorMessage("quantity", msg); }
	public String getQuantity() { return getValue("quantity"); }
	public String getQuantity(String defaultValue) { return getValue("quantity", defaultValue); }
	public int getQuantityInt() { String s = getValue("quantity"); return s == null ? -1 : Integer.parseInt(s); }
	public int getQuantityInt(int defaultValue) { String s = getValue("quantity"); return s == null ? defaultValue : Integer.parseInt(s); }
	public void setQuantity(String value) { setValue("quantity", value); }
	public void setQuantity(int value) { setValue("quantity", Integer.toString(value)); }

	public boolean isRefillsValueSet() { return hasValue("refills"); }
	public boolean isRefillsFlagSet(long flag) { return flagIsSet("refills", flag); }
	public void setRefillsFlag(long flag) { setFlag("refills", flag); }
	public void clearRefillsFlag(long flag) { clearFlag("refills", flag); }
	public String getRefillsRequestParam() { return request.getParameter("_dc.refills"); }
	public DialogField getRefillsField() { return getField("refills"); }
	public DialogContext.DialogFieldState getRefillsFieldState() { return getFieldState("refills"); }
	public void addRefillsErrorMsg(String msg) { addErrorMessage("refills", msg); }
	public String getRefills() { return getValue("refills"); }
	public String getRefills(String defaultValue) { return getValue("refills", defaultValue); }
	public int getRefillsInt() { String s = getValue("refills"); return s == null ? -1 : Integer.parseInt(s); }
	public int getRefillsInt(int defaultValue) { String s = getValue("refills"); return s == null ? defaultValue : Integer.parseInt(s); }
	public void setRefills(String value) { setValue("refills", value); }
	public void setRefills(int value) { setValue("refills", Integer.toString(value)); }

	public boolean isGenallowedValueSet() { return hasValue("genallowed"); }
	public boolean isGenallowedFlagSet(long flag) { return flagIsSet("genallowed", flag); }
	public void setGenallowedFlag(long flag) { setFlag("genallowed", flag); }
	public void clearGenallowedFlag(long flag) { clearFlag("genallowed", flag); }
	public String getGenallowedRequestParam() { return request.getParameter("_dc.genallowed"); }
	public DialogField getGenallowedField() { return getField("genallowed"); }
	public DialogContext.DialogFieldState getGenallowedFieldState() { return getFieldState("genallowed"); }
	public void addGenallowedErrorMsg(String msg) { addErrorMessage("genallowed", msg); }
	public boolean getGenallowed() { Boolean o = (Boolean) getValueAsObject("genallowed"); return o == null ? false : o.booleanValue(); }
	public boolean getGenallowed(boolean defaultValue) { Boolean o = (Boolean) getValueAsObject("genallowed"); return o == null ? defaultValue : o.booleanValue(); }
	public void setGenallowed(boolean value) { setValue("genallowed", value == true ? "1" : "0"); }

	public boolean isInstructionsValueSet() { return hasValue("instructions"); }
	public boolean isInstructionsFlagSet(long flag) { return flagIsSet("instructions", flag); }
	public void setInstructionsFlag(long flag) { setFlag("instructions", flag); }
	public void clearInstructionsFlag(long flag) { clearFlag("instructions", flag); }
	public String getInstructionsRequestParam() { return request.getParameter("_dc.instructions"); }
	public DialogField getInstructionsField() { return getField("instructions"); }
	public DialogContext.DialogFieldState getInstructionsFieldState() { return getFieldState("instructions"); }
	public void addInstructionsErrorMsg(String msg) { addErrorMessage("instructions", msg); }
	public int getInstructions() { Integer o = (Integer) getValueAsObject("instructions"); return o == null ? 0 : o.intValue(); }
	public int getInstructions(int defaultValue) { Integer o = (Integer) getValueAsObject("instructions"); return o == null ? defaultValue : o.intValue(); }
	public void setInstructions(int value) { setValue("instructions", Integer.toString(value)); }

}
