
/* this file is generated by com.netspective.sparx.xaf.form.Dialog.getSubclassedDialogContextCode(), do not modify (you can extend it, though) */

package dialog.context.Test;

import com.netspective.sparx.xaf.form.*;

public class DialogTest10Context extends DialogContext
{
	public boolean isCheckboxFieldValueSet() { return hasValue("checkbox_field"); }
	public boolean isCheckboxFieldFlagSet(long flag) { return flagIsSet("checkbox_field", flag); }
	public void setCheckboxFieldFlag(long flag) { setFlag("checkbox_field", flag); }
	public void clearCheckboxFieldFlag(long flag) { clearFlag("checkbox_field", flag); }
	public String getCheckboxFieldRequestParam() { return request.getParameter("_dc.checkbox_field"); }
	public DialogField getCheckboxFieldField() { return getField("checkbox_field"); }
	public DialogContext.DialogFieldState getCheckboxFieldFieldState() { return getFieldState("checkbox_field"); }
	public void addCheckboxFieldErrorMsg(String msg) { addErrorMessage("checkbox_field", msg); }
	public boolean getCheckboxField() { Boolean o = (Boolean) getValueAsObject("checkbox_field"); return o == null ? false : o.booleanValue(); }
	public boolean getCheckboxField(boolean defaultValue) { Boolean o = (Boolean) getValueAsObject("checkbox_field"); return o == null ? defaultValue : o.booleanValue(); }
	public void setCheckboxField(boolean value) { setValue("checkbox_field", value == true ? "1" : "0"); }

	public boolean isStaticField2ValueSet() { return hasValue("static_field2"); }
	public boolean isStaticField2FlagSet(long flag) { return flagIsSet("static_field2", flag); }
	public void setStaticField2Flag(long flag) { setFlag("static_field2", flag); }
	public void clearStaticField2Flag(long flag) { clearFlag("static_field2", flag); }
	public String getStaticField2RequestParam() { return request.getParameter("_dc.static_field2"); }
	public DialogField getStaticField2Field() { return getField("static_field2"); }
	public DialogContext.DialogFieldState getStaticField2FieldState() { return getFieldState("static_field2"); }
	public void addStaticField2ErrorMsg(String msg) { addErrorMessage("static_field2", msg); }
	public String getStaticField2() { return getValue("static_field2"); }
	public String getStaticField2(String defaultValue) { return getValue("static_field2", defaultValue); }
	public String getStaticField2OrBlank() { return getValue("static_field2", ""); }
	public void setStaticField2(String value) { setValue("static_field2", value); }

	public boolean isTextField1ValueSet() { return hasValue("text_field_1"); }
	public boolean isTextField1FlagSet(long flag) { return flagIsSet("text_field_1", flag); }
	public void setTextField1Flag(long flag) { setFlag("text_field_1", flag); }
	public void clearTextField1Flag(long flag) { clearFlag("text_field_1", flag); }
	public String getTextField1RequestParam() { return request.getParameter("_dc.text_field_1"); }
	public DialogField getTextField1Field() { return getField("text_field_1"); }
	public DialogContext.DialogFieldState getTextField1FieldState() { return getFieldState("text_field_1"); }
	public void addTextField1ErrorMsg(String msg) { addErrorMessage("text_field_1", msg); }
	public String getTextField1() { return getValue("text_field_1"); }
	public String getTextField1(String defaultValue) { return getValue("text_field_1", defaultValue); }
	public String getTextField1OrBlank() { return getValue("text_field_1", ""); }
	public void setTextField1(String value) { setValue("text_field_1", value); }

	public boolean isSelectFieldValueSet() { return hasValue("select_field"); }
	public boolean isSelectFieldFlagSet(long flag) { return flagIsSet("select_field", flag); }
	public void setSelectFieldFlag(long flag) { setFlag("select_field", flag); }
	public void clearSelectFieldFlag(long flag) { clearFlag("select_field", flag); }
	public String getSelectFieldRequestParam() { return request.getParameter("_dc.select_field"); }
	public DialogField getSelectFieldField() { return getField("select_field"); }
	public DialogContext.DialogFieldState getSelectFieldFieldState() { return getFieldState("select_field"); }
	public void addSelectFieldErrorMsg(String msg) { addErrorMessage("select_field", msg); }
	public String getSelectField() { return getValue("select_field"); }
	public String getSelectField(String defaultValue) { return getValue("select_field", defaultValue); }
	public int getSelectFieldInt() { String s = getValue("select_field"); return s == null ? -1 : Integer.parseInt(s); }
	public int getSelectFieldInt(int defaultValue) { String s = getValue("select_field"); return s == null ? defaultValue : Integer.parseInt(s); }
	public void setSelectField(String value) { setValue("select_field", value); }
	public void setSelectField(int value) { setValue("select_field", Integer.toString(value)); }

	public boolean isStaticField4ValueSet() { return hasValue("static_field_4"); }
	public boolean isStaticField4FlagSet(long flag) { return flagIsSet("static_field_4", flag); }
	public void setStaticField4Flag(long flag) { setFlag("static_field_4", flag); }
	public void clearStaticField4Flag(long flag) { clearFlag("static_field_4", flag); }
	public String getStaticField4RequestParam() { return request.getParameter("_dc.static_field_4"); }
	public DialogField getStaticField4Field() { return getField("static_field_4"); }
	public DialogContext.DialogFieldState getStaticField4FieldState() { return getFieldState("static_field_4"); }
	public void addStaticField4ErrorMsg(String msg) { addErrorMessage("static_field_4", msg); }
	public String getStaticField4() { return getValue("static_field_4"); }
	public String getStaticField4(String defaultValue) { return getValue("static_field_4", defaultValue); }
	public String getStaticField4OrBlank() { return getValue("static_field_4", ""); }
	public void setStaticField4(String value) { setValue("static_field_4", value); }

}
