
/* this file is generated by com.netspective.sparx.xaf.form.Dialog.getSubclassedDialogContextCode(), do not modify (you can extend it, though) */

package dialog.context.Test;

import com.netspective.sparx.xaf.form.*;

public class DialogTest03Context extends DialogContext
{
	public boolean isSelFieldComboValueSet() { return hasValue("sel_field_combo"); }
	public boolean isSelFieldComboFlagSet(long flag) { return flagIsSet("sel_field_combo", flag); }
	public void setSelFieldComboFlag(long flag) { setFlag("sel_field_combo", flag); }
	public void clearSelFieldComboFlag(long flag) { clearFlag("sel_field_combo", flag); }
	public String getSelFieldComboRequestParam() { return request.getParameter("_dc.sel_field_combo"); }
	public DialogField getSelFieldComboField() { return getField("sel_field_combo"); }
	public DialogContext.DialogFieldState getSelFieldComboFieldState() { return getFieldState("sel_field_combo"); }
	public void addSelFieldComboErrorMsg(String msg) { addErrorMessage("sel_field_combo", msg); }
	public String getSelFieldCombo() { return getValue("sel_field_combo"); }
	public String getSelFieldCombo(String defaultValue) { return getValue("sel_field_combo", defaultValue); }
	public int getSelFieldComboInt() { String s = getValue("sel_field_combo"); return s == null ? -1 : Integer.parseInt(s); }
	public int getSelFieldComboInt(int defaultValue) { String s = getValue("sel_field_combo"); return s == null ? defaultValue : Integer.parseInt(s); }
	public void setSelFieldCombo(String value) { setValue("sel_field_combo", value); }
	public void setSelFieldCombo(int value) { setValue("sel_field_combo", Integer.toString(value)); }

	public boolean isSelFieldRadioValueSet() { return hasValue("sel_field_radio"); }
	public boolean isSelFieldRadioFlagSet(long flag) { return flagIsSet("sel_field_radio", flag); }
	public void setSelFieldRadioFlag(long flag) { setFlag("sel_field_radio", flag); }
	public void clearSelFieldRadioFlag(long flag) { clearFlag("sel_field_radio", flag); }
	public String getSelFieldRadioRequestParam() { return request.getParameter("_dc.sel_field_radio"); }
	public DialogField getSelFieldRadioField() { return getField("sel_field_radio"); }
	public DialogContext.DialogFieldState getSelFieldRadioFieldState() { return getFieldState("sel_field_radio"); }
	public void addSelFieldRadioErrorMsg(String msg) { addErrorMessage("sel_field_radio", msg); }
	public String getSelFieldRadio() { return getValue("sel_field_radio"); }
	public String getSelFieldRadio(String defaultValue) { return getValue("sel_field_radio", defaultValue); }
	public int getSelFieldRadioInt() { String s = getValue("sel_field_radio"); return s == null ? -1 : Integer.parseInt(s); }
	public int getSelFieldRadioInt(int defaultValue) { String s = getValue("sel_field_radio"); return s == null ? defaultValue : Integer.parseInt(s); }
	public void setSelFieldRadio(String value) { setValue("sel_field_radio", value); }
	public void setSelFieldRadio(int value) { setValue("sel_field_radio", Integer.toString(value)); }

	public boolean isSelFieldListValueSet() { return hasValue("sel_field_list"); }
	public boolean isSelFieldListFlagSet(long flag) { return flagIsSet("sel_field_list", flag); }
	public void setSelFieldListFlag(long flag) { setFlag("sel_field_list", flag); }
	public void clearSelFieldListFlag(long flag) { clearFlag("sel_field_list", flag); }
	public String getSelFieldListRequestParam() { return request.getParameter("_dc.sel_field_list"); }
	public DialogField getSelFieldListField() { return getField("sel_field_list"); }
	public DialogContext.DialogFieldState getSelFieldListFieldState() { return getFieldState("sel_field_list"); }
	public void addSelFieldListErrorMsg(String msg) { addErrorMessage("sel_field_list", msg); }
	public String getSelFieldList() { return getValue("sel_field_list"); }
	public String getSelFieldList(String defaultValue) { return getValue("sel_field_list", defaultValue); }
	public int getSelFieldListInt() { String s = getValue("sel_field_list"); return s == null ? -1 : Integer.parseInt(s); }
	public int getSelFieldListInt(int defaultValue) { String s = getValue("sel_field_list"); return s == null ? defaultValue : Integer.parseInt(s); }
	public void setSelFieldList(String value) { setValue("sel_field_list", value); }
	public void setSelFieldList(int value) { setValue("sel_field_list", Integer.toString(value)); }

	public boolean isSelFieldMultilistValueSet() { return hasValue("sel_field_multilist"); }
	public boolean isSelFieldMultilistFlagSet(long flag) { return flagIsSet("sel_field_multilist", flag); }
	public void setSelFieldMultilistFlag(long flag) { setFlag("sel_field_multilist", flag); }
	public void clearSelFieldMultilistFlag(long flag) { clearFlag("sel_field_multilist", flag); }
	public String getSelFieldMultilistRequestParam() { return request.getParameter("_dc.sel_field_multilist"); }
	public DialogField getSelFieldMultilistField() { return getField("sel_field_multilist"); }
	public DialogContext.DialogFieldState getSelFieldMultilistFieldState() { return getFieldState("sel_field_multilist"); }
	public void addSelFieldMultilistErrorMsg(String msg) { addErrorMessage("sel_field_multilist", msg); }
	public String[] getSelFieldMultilist() { return getValues("sel_field_multilist"); }
	public String[] getSelFieldMultilist(String[] defaultValue) { String[] o = getValues("sel_field_multilist"); return o == null ? defaultValue : o; }
	public void setSelFieldMultilist(String[] values) { setValues("sel_field_multilist", values); }

	public boolean isSelFieldMulticheckValueSet() { return hasValue("sel_field_multicheck"); }
	public boolean isSelFieldMulticheckFlagSet(long flag) { return flagIsSet("sel_field_multicheck", flag); }
	public void setSelFieldMulticheckFlag(long flag) { setFlag("sel_field_multicheck", flag); }
	public void clearSelFieldMulticheckFlag(long flag) { clearFlag("sel_field_multicheck", flag); }
	public String getSelFieldMulticheckRequestParam() { return request.getParameter("_dc.sel_field_multicheck"); }
	public DialogField getSelFieldMulticheckField() { return getField("sel_field_multicheck"); }
	public DialogContext.DialogFieldState getSelFieldMulticheckFieldState() { return getFieldState("sel_field_multicheck"); }
	public void addSelFieldMulticheckErrorMsg(String msg) { addErrorMessage("sel_field_multicheck", msg); }
	public String[] getSelFieldMulticheck() { return getValues("sel_field_multicheck"); }
	public String[] getSelFieldMulticheck(String[] defaultValue) { String[] o = getValues("sel_field_multicheck"); return o == null ? defaultValue : o; }
	public void setSelFieldMulticheck(String[] values) { setValues("sel_field_multicheck", values); }

	public boolean isSelFieldMultidualValueSet() { return hasValue("sel_field_multidual"); }
	public boolean isSelFieldMultidualFlagSet(long flag) { return flagIsSet("sel_field_multidual", flag); }
	public void setSelFieldMultidualFlag(long flag) { setFlag("sel_field_multidual", flag); }
	public void clearSelFieldMultidualFlag(long flag) { clearFlag("sel_field_multidual", flag); }
	public String getSelFieldMultidualRequestParam() { return request.getParameter("_dc.sel_field_multidual"); }
	public DialogField getSelFieldMultidualField() { return getField("sel_field_multidual"); }
	public DialogContext.DialogFieldState getSelFieldMultidualFieldState() { return getFieldState("sel_field_multidual"); }
	public void addSelFieldMultidualErrorMsg(String msg) { addErrorMessage("sel_field_multidual", msg); }
	public String[] getSelFieldMultidual() { return getValues("sel_field_multidual"); }
	public String[] getSelFieldMultidual(String[] defaultValue) { String[] o = getValues("sel_field_multidual"); return o == null ? defaultValue : o; }
	public void setSelFieldMultidual(String[] values) { setValues("sel_field_multidual", values); }

}
