
/* this file is generated by com.netspective.sparx.xaf.form.Dialog.getSubclassedDialogContextCode(), do not modify (you can extend it, though) */

package dialog.context.Test;

import java.util.Date;
import com.netspective.sparx.xaf.form.*;

public class DialogTest08Context extends DialogContext
{
	public boolean isSsnFieldValueSet() { return hasValue("ssn_field"); }
	public boolean isSsnFieldFlagSet(long flag) { return flagIsSet("ssn_field", flag); }
	public void setSsnFieldFlag(long flag) { setFlag("ssn_field", flag); }
	public void clearSsnFieldFlag(long flag) { clearFlag("ssn_field", flag); }
	public String getSsnFieldRequestParam() { return request.getParameter("_dc.ssn_field"); }
	public DialogField getSsnFieldField() { return getField("ssn_field"); }
	public DialogContext.DialogFieldState getSsnFieldFieldState() { return getFieldState("ssn_field"); }
	public void addSsnFieldErrorMsg(String msg) { addErrorMessage("ssn_field", msg); }
	public String getSsnField() { return getValue("ssn_field"); }
	public String getSsnField(String defaultValue) { return getValue("ssn_field", defaultValue); }
	public String getSsnFieldOrBlank() { return getValue("ssn_field", ""); }
	public void setSsnField(String value) { setValue("ssn_field", value); }

	public boolean isDateFieldValueSet() { return hasValue("date_field"); }
	public boolean isDateFieldFlagSet(long flag) { return flagIsSet("date_field", flag); }
	public void setDateFieldFlag(long flag) { setFlag("date_field", flag); }
	public void clearDateFieldFlag(long flag) { clearFlag("date_field", flag); }
	public String getDateFieldRequestParam() { return request.getParameter("_dc.date_field"); }
	public DialogField getDateFieldField() { return getField("date_field"); }
	public DialogContext.DialogFieldState getDateFieldFieldState() { return getFieldState("date_field"); }
	public void addDateFieldErrorMsg(String msg) { addErrorMessage("date_field", msg); }
	public Date getDateField() { return (Date) getValueAsObject("date_field"); }
	public Date getDateField(Date defaultValue) { return (Date) getValueAsObject("date_field", defaultValue); }
	public void setDateField(String value) { setValue("date_field", value); }

	public boolean isPhoneFieldValueSet() { return hasValue("phone_field"); }
	public boolean isPhoneFieldFlagSet(long flag) { return flagIsSet("phone_field", flag); }
	public void setPhoneFieldFlag(long flag) { setFlag("phone_field", flag); }
	public void clearPhoneFieldFlag(long flag) { clearFlag("phone_field", flag); }
	public String getPhoneFieldRequestParam() { return request.getParameter("_dc.phone_field"); }
	public DialogField getPhoneFieldField() { return getField("phone_field"); }
	public DialogContext.DialogFieldState getPhoneFieldFieldState() { return getFieldState("phone_field"); }
	public void addPhoneFieldErrorMsg(String msg) { addErrorMessage("phone_field", msg); }
	public String getPhoneField() { return getValue("phone_field"); }
	public String getPhoneField(String defaultValue) { return getValue("phone_field", defaultValue); }
	public String getPhoneFieldOrBlank() { return getValue("phone_field", ""); }
	public void setPhoneField(String value) { setValue("phone_field", value); }

}
