
/* this file is generated by com.netspective.sparx.util.xml.XmlSource.createNodeIdentifiersClass(), do not modify (you can extend it, though) */

package id.statement;

public class Gift
{
    static public final String GETGIFTPICTURE = "Gift.getGiftPicture";
    static public final String GIFTDETAIL = "Gift.GiftDetail";
    static public final String GIFTSPICKED = "Gift.GiftsPicked";
    static public final String GIFTSTOPICK = "Gift.GiftsToPick";
    static public final String INSERTINTOMYGIFTLIST = "Gift.InsertIntoMyGiftList";
    static public final String PICKEDGIFTDETAIL = "Gift.PickedGiftDetail";
    static public final String REMOVEFROMMYGIFTLIST = "Gift.RemoveFromMyGiftList";
    static public final String YOURGIFTLIST = "Gift.YourGiftList";
}
