
/* this file is generated by com.netspective.sparx.util.xml.XmlSource.createNodeIdentifiersClass(), do not modify (you can extend it, though) */

package id.statement;

public class User
{
    static public final String ADMINRELATIONSHIPS = "User.adminRelationships";
    static public final String COMBO_USER_LIST = "User.combo_user_list";
    static public final String LOGIN = "User.login";
    static public final String REALTIONSHIPS_ALLOWED = "User.realtionships_allowed";
    static public final String SHAREDPASSWORD = "User.sharedPassword";
    static public final String USER_LIST = "User.user_list";
    static public final String USER_RELATIONSHIP = "User.user_relationship";
    static public final String USERDETAIL = "User.UserDetail";
}
