
/* this file is generated by com.netspective.sparx.util.xml.XmlSource.createNodeIdentifiersClass(), do not modify (you can extend it, though) */

package id.config;

public class App
{
    static public final String DOCUMENTS_ROOT_PATH = "app.documents-root-path";
    static public final String REPORT_FILE_DOWNLOAD_URL = "app.report-file-download-url";
    static public final String REPORT_FILE_STORE_PATH = "app.report-file-store-path";
    static public final String SITE_ROOT_PATH = "app.site-root-path";
    static public final String SITE_TEMP_PATH = "app.site-temp-path";
    static public final String WEB_INF_ROOT_PATH = "app.web-inf-root-path";
}
