/*
 * JSP generated by Resin 2.1.0 (built Tue Mar 26 14:12:50 PST 2002)
 */

import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _index__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.jsp.QPageContext pageContext = (com.caucho.jsp.QPageContext) com.caucho.jsp.QJspFactory.create().getPageContext(this, request, response, null, true, 8192, true);
    javax.servlet.jsp.JspWriter out = (javax.servlet.jsp.JspWriter) pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.http.HttpSession session = pageContext.getSession();
    javax.servlet.ServletContext application = pageContext.getServletContext();
    response.setContentType("text/html");
    app.tag.PageTag _jsp_tag0 = null;
    try {
      pageContext.write(_jsp_string0, 0, _jsp_string0.length);
      pageContext.write(_jsp_string1, 0, _jsp_string1.length);
      if (_jsp_tag0 == null) {
        _jsp_tag0 = new app.tag.PageTag();
        _jsp_tag0.setPageContext(pageContext);
        _jsp_tag0.setParent((javax.servlet.jsp.tagext.Tag) null);
          _jsp_tag0.setHeading("Welcome to Baby Registry");
          _jsp_tag0.setTitle("Baby Registry");
      }

      int _jspEval1 = _jsp_tag0.doStartTag();
      if (_jspEval1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        pageContext.write(_jsp_string2, 0, _jsp_string2.length);
      }
      int _jsp_endTagVar2 = _jsp_tag0.doEndTag();
      if (_jsp_endTagVar2 == javax.servlet.jsp.tagext.Tag.SKIP_PAGE)
        return;
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_tag0 != null)
        _jsp_tag0.release();
      JspFactory.getDefaultFactory().releasePageContext(pageContext);
    }
  }

  private com.caucho.java.LineMap _caucho_line_map;
  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != 2057024142)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Depend depend;
      depend = (com.caucho.vfs.Depend) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public com.caucho.java.LineMap _caucho_getLineMap()
  {
    return _caucho_line_map;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.java.LineMap lineMap,
                   com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    mergePath.addClassPath(getClass().getClassLoader());
    _caucho_line_map = new com.caucho.java.LineMap("_index__jsp.java", "/babyreg/index.jsp");
    _caucho_line_map.add(1, 1);
    _caucho_line_map.add(1, 26);
    _caucho_line_map.add(4, 28);
    _caucho_line_map.add(4, 38);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("index.jsp"), 1026789611888L, 1195L);
    _caucho_depends.add(depend);
  }

  private static byte []_jsp_string1;
  private static byte []_jsp_string2;
  private static byte []_jsp_string0;
  static {
    _jsp_string1 = "\r\n\r\n".getBytes();
    _jsp_string2 = "\r\n<b>Hello everyone!!</b><br>\r\nThanks, for visiting our baby registry.  On the left you will find<br>\r\na set of links that will get through the gift picking process.<br><br>\r\nAgain, pardon the simple look of the site, it will be prettier soon.<br><br>\r\n\r\n<b>See what I got</b><br>\r\nThis is the list of gifts that have already been bought.<br><br>\r\n<b>Pick a Gift</b><br>\r\nThis is the list of gifts that are still needed.<br>\r\nEvery item listed here can be found in <i>Babies R Us</i> except for<br>\r\nthe two \"Sleep 'n Play Set\" clothing items which are from <i>Target</i>.<br><br>\r\n<b>View your Gift List</b><br>\r\nThis is where you see all the gifts you have picked.<br><br>\r\n<b>Tell me What you got</b><br>\r\nIf you had already bought a present or had something else in bind,<br>\r\nsimply describe it.<br><br>\r\n<b>Make a suggestion</b><br>\r\nIf you know of something that is not anywhere in the site,<br>\r\nbut you know I will need or you think is cool, also describe it.<br><br>\r\n\r\n\r\n".getBytes();
    _jsp_string0 = "\r\n".getBytes();
  }
}
