
/* this file is generated by com.netspective.sparx.util.xml.XmlSource.createNodeIdentifiersClass(), do not modify (you can extend it, though) */

package id.config.sparx.ace.metrics;

public class Filesys
{
    static public final String CODE_EXTENSIONS = "sparx.ace.metrics.filesys.code-extensions";
    static public final String IGNORE_CASE = "sparx.ace.metrics.filesys.ignore-case";
}
