/*
 * Created by IntelliJ IDEA.
 * User: snshah
 * Date: Nov 3, 2001
 * Time: 10:05:45 PM
 * To change template for new interface use 
 * Code Style | Class Templates options (Tools | IDE Options).
 */
package com.xaf.db;

import com.xaf.value.ValueContext;
import com.xaf.value.SingleValueSource;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

public interface DatabasePolicy
{
    /**
     * When an auto increment value is needed in a SQL insert, this method is called before the execution of the insert
     * statement. This gives the DatabasePolicy to go get a sequence value or do whatever is
     * necessary in order to fill in the auto inc value into the columnNames, columnValues (which are the DML items
     * being filled out by the DmlTask object. In case sequences are not used, this method will just do nothing and
     * wait for the handleAutoIncPostDmlExecute to be called.
     *
     * @param conn The database connection to use
     * @param seqOrTableName The sequence name or the table name
     * @param autoIncColumnName The name of the column that is the auto inc column
     * @returns The auto inc value generated by the database or null if not known yet
     */
    public Object handleAutoIncPreDmlExecute(Connection conn, String seqOrTableName, String autoIncColumnName) throws SQLException;

    /**
     * When an auto increment value is needed in a SQL DML, this method is called after the execution of the DML
     * (insert, update, or delete). This gives the DatabasePolicy to go get a sequence value or do whatever is
     * necessary in order to return the auto inc value.
     *
     * @param conn The database connection to use
     * @param vc The ValueContext being used to fill the DmlTask columns and values
     * @param seqOrTableName The sequence name or the table name
     * @param autoIncColumnName The name of the column that is the auto inc column
     * @param autoIncColumnValue The value of the auto inc column returned by handleAutoIncPreDmlExecute method
     * @returns The auto inc value generated by the database or null if not known yet
     */

    public Object handleAutoIncPostDmlExecute(Connection conn, String seqOrTableName, String autoIncColumnName, Object autoIncColumnValue) throws SQLException;
    /**
     * When an auto increment value is needed in a SQL insert, this method is called before the execution of the insert
     * statement. This gives the DatabasePolicy to go get a sequence value or do whatever is
     * necessary in order to fill in the auto inc value into the columnNames, columnValues (which are the DML items
     * being filled out by the DmlTask object. In case sequences are not used, this method will just do nothing and
     * wait for the handleAutoIncPostDmlExecute to be called.
     *
     * @param conn The database connection to use
     * @param vc The ValueContext being used to fill the DmlTask columns and values
     * @param seqOrTableName The sequence name or the table name
     * @param autoIncColumnName The name of the column that is the auto inc column
     * @param columnNames The list of column names prepared for use in the DmlTask prior to calling this method
     * @param columnValues The list of column values prepared for use in the DmlTask prior to calling this method
     * @returns The auto inc value generated by the database or null if not known yet
     */

    public Object handleAutoIncPreDmlExecute(Connection conn, ValueContext vc, String seqOrTableName, String autoIncColumnName, List columnNames, List columnValues) throws SQLException;

    /**
     * When an auto increment value is needed in a SQL DML, this method is called after the execution of the DML
     * (insert, update, or delete). This gives the DatabasePolicy to go get a sequence value or do whatever is
     * necessary in order to return the auto inc value.
     *
     * @param conn The database connection to use
     * @param vc The ValueContext being used to fill the DmlTask columns and values
     * @param seqOrTableName The sequence name or the table name
     * @param autoIncColumnName The name of the column that is the auto inc column
     * @param autoIncColumnValue The value of the auto inc column returned by handleAutoIncPreDmlExecute method
     * @returns The auto inc value generated by the database or null if not known yet
     */
    public Object handleAutoIncPostDmlExecute(Connection conn, ValueContext vc, String seqOrTableName, String autoIncColumnName, Object autoIncColumnValue) throws SQLException;

    /**
     * Gets the current value of an auto increment column.
     *
     * @param conn The database connection to use
     * @param vc The ValueContext being used to fill the DmlTask columns and values
     * @param seqOrTableName The sequence name or the table name
     * @param autoIncColumnName The name of the column that is the auto inc column
     * @returns The auto inc value generated by the database or null if not known yet
     */
    public Object getAutoIncCurrentValue(Connection conn, ValueContext vc, String seqOrTableName, String autoIncColumnName) throws SQLException;
}
