
/* this file is generated by com.netspective.sparx.util.xml.XmlSource.createNodeIdentifiersClass(), do not modify (you can extend it, though) */

package id.config.sparx.shared;

public class Report
{
    static public final String ROW_SEP_IMG_SRC = "sparx.shared.report.row-sep-img-src";
    static public final String SORT_ASCENDING_IMG_SRC = "sparx.shared.report.sort-ascending-img-src";
    static public final String SORT_DESCENDING_IMG_SRC = "sparx.shared.report.sort-descending-img-src";
}
