
/* this file is generated by com.netspective.sparx.util.xml.XmlSource.createNodeIdentifiersClass(), do not modify (you can extend it, though) */

package id.config.app;

public class Schema
{
    static public final String ROOT_PATH = "app.schema.root-path";
    static public final String SOURCE_FILE = "app.schema.source-file";
}
