
/* this file is generated by com.netspective.sparx.util.xml.XmlSource.createNodeIdentifiersClass(), do not modify (you can extend it, though) */

package id.config.app;

public class Security
{
    static public final String ACL_FILE = "app.security.acl-file";
    static public final String ROOT_PATH = "app.security.root-path";
}
