
/* this file is generated by com.netspective.sparx.util.xml.XmlSource.createNodeIdentifiersClass(), do not modify (you can extend it, though) */

package id.config.app;

public class Sql
{
    static public final String ROOT_PATH = "app.sql.root-path";
    static public final String SOURCE_FILE = "app.sql.source-file";
}
