
/* this file is generated by com.netspective.sparx.util.xml.XmlSource.createNodeIdentifiersClass(), do not modify (you can extend it, though) */

package id.config.app;

public class Ui
{
    static public final String ROOT_PATH = "app.ui.root-path";
    static public final String SOURCE_FILE = "app.ui.source-file";
    static public final String STRUCTURE_FILE = "app.ui.structure-file";
}
