
/* this file is generated by com.netspective.sparx.util.xml.XmlSource.createNodeIdentifiersClass(), do not modify (you can extend it, though) */

package id.config.sparx.ace.login;

public class User
{
    static public final String SESSION_ATTR_NAME = "sparx.ace.login.user.session-attr-name";
}
