
/* this file is generated by com.netspective.sparx.util.xml.XmlSource.createNodeIdentifiersClass(), do not modify (you can extend it, though) */

package id.config.sparx.ace.login;

public class UserId
{
    static public final String COOKIE_NAME = "sparx.ace.login.user-id.cookie-name";
}
