
/* this file is generated by com.netspective.sparx.xaf.form.Dialog.getSubclassedDialogContextCode(), do not modify (you can extend it, though) */

package dialog.context.tutorial;

import com.netspective.sparx.xaf.form.*;

public class HelloSecondContext extends DialogContext
{
	public boolean isPersonNameValueSet() { return hasValue("personName"); }
	public boolean isPersonNameFlagSet(long flag) { return flagIsSet("personName", flag); }
	public void setPersonNameFlag(long flag) { setFlag("personName", flag); }
	public void clearPersonNameFlag(long flag) { clearFlag("personName", flag); }
	public String getPersonNameRequestParam() { return request.getParameter("_dc.personName"); }
	public DialogField getPersonNameField() { return getField("personName"); }
	public DialogContext.DialogFieldState getPersonNameFieldState() { return getFieldState("personName"); }
	public void addPersonNameErrorMsg(String msg) { addErrorMessage("personName", msg); }
	public String getPersonName() { return getValue("personName"); }
	public String getPersonName(String defaultValue) { return getValue("personName", defaultValue); }
	public String getPersonNameOrBlank() { return getValue("personName", ""); }
	public void setPersonName(String value) { setValue("personName", value); }

	public boolean isPersonGenderValueSet() { return hasValue("personGender"); }
	public boolean isPersonGenderFlagSet(long flag) { return flagIsSet("personGender", flag); }
	public void setPersonGenderFlag(long flag) { setFlag("personGender", flag); }
	public void clearPersonGenderFlag(long flag) { clearFlag("personGender", flag); }
	public String getPersonGenderRequestParam() { return request.getParameter("_dc.personGender"); }
	public DialogField getPersonGenderField() { return getField("personGender"); }
	public DialogContext.DialogFieldState getPersonGenderFieldState() { return getFieldState("personGender"); }
	public void addPersonGenderErrorMsg(String msg) { addErrorMessage("personGender", msg); }
	public String getPersonGender() { return getValue("personGender"); }
	public String getPersonGender(String defaultValue) { return getValue("personGender", defaultValue); }
	public int getPersonGenderInt() { String s = getValue("personGender"); return s == null ? -1 : Integer.parseInt(s); }
	public int getPersonGenderInt(int defaultValue) { String s = getValue("personGender"); return s == null ? defaultValue : Integer.parseInt(s); }
	public void setPersonGender(String value) { setValue("personGender", value); }
	public void setPersonGender(int value) { setValue("personGender", Integer.toString(value)); }

	public boolean isPersonAgeValueSet() { return hasValue("personAge"); }
	public boolean isPersonAgeFlagSet(long flag) { return flagIsSet("personAge", flag); }
	public void setPersonAgeFlag(long flag) { setFlag("personAge", flag); }
	public void clearPersonAgeFlag(long flag) { clearFlag("personAge", flag); }
	public String getPersonAgeRequestParam() { return request.getParameter("_dc.personAge"); }
	public DialogField getPersonAgeField() { return getField("personAge"); }
	public DialogContext.DialogFieldState getPersonAgeFieldState() { return getFieldState("personAge"); }
	public void addPersonAgeErrorMsg(String msg) { addErrorMessage("personAge", msg); }
	public int getPersonAge() { Integer o = (Integer) getValueAsObject("personAge"); return o == null ? 0 : o.intValue(); }
	public int getPersonAge(int defaultValue) { Integer o = (Integer) getValueAsObject("personAge"); return o == null ? defaultValue : o.intValue(); }
	public void setPersonAge(int value) { setValue("personAge", Integer.toString(value)); }

}
