
/* this file is generated by com.netspective.sparx.xaf.form.Dialog.getSubclassedDialogContextCode(), do not modify (you can extend it, though) */

package dialog.context.tutorial;

import com.netspective.sparx.xaf.form.*;

public class HelloFirstContext extends DialogContext
{
	public boolean isPersonNameValueSet() { return hasValue("personName"); }
	public boolean isPersonNameFlagSet(long flag) { return flagIsSet("personName", flag); }
	public void setPersonNameFlag(long flag) { setFlag("personName", flag); }
	public void clearPersonNameFlag(long flag) { clearFlag("personName", flag); }
	public String getPersonNameRequestParam() { return request.getParameter("_dc.personName"); }
	public DialogField getPersonNameField() { return getField("personName"); }
	public DialogContext.DialogFieldState getPersonNameFieldState() { return getFieldState("personName"); }
	public void addPersonNameErrorMsg(String msg) { addErrorMessage("personName", msg); }
	public String getPersonName() { return getValue("personName"); }
	public String getPersonName(String defaultValue) { return getValue("personName", defaultValue); }
	public String getPersonNameOrBlank() { return getValue("personName", ""); }
	public void setPersonName(String value) { setValue("personName", value); }

}
