
/* this file is generated by com.netspective.sparx.xaf.form.Dialog.getSubclassedDialogContextCode(), do not modify (you can extend it, though) */

package dialog.context.Test;

import com.netspective.sparx.xaf.form.*;

public class DialogTest14Context extends DialogContext
{
	public boolean isTextFieldValueSet() { return hasValue("text_field"); }
	public boolean isTextFieldFlagSet(long flag) { return flagIsSet("text_field", flag); }
	public void setTextFieldFlag(long flag) { setFlag("text_field", flag); }
	public void clearTextFieldFlag(long flag) { clearFlag("text_field", flag); }
	public String getTextFieldRequestParam() { return request.getParameter("_dc.text_field"); }
	public DialogField getTextFieldField() { return getField("text_field"); }
	public DialogContext.DialogFieldState getTextFieldFieldState() { return getFieldState("text_field"); }
	public void addTextFieldErrorMsg(String msg) { addErrorMessage("text_field", msg); }
	public String getTextField() { return getValue("text_field"); }
	public String getTextField(String defaultValue) { return getValue("text_field", defaultValue); }
	public String getTextFieldOrBlank() { return getValue("text_field", ""); }
	public void setTextField(String value) { setValue("text_field", value); }

	public boolean isSelectField01ValueSet() { return hasValue("select_field_01"); }
	public boolean isSelectField01FlagSet(long flag) { return flagIsSet("select_field_01", flag); }
	public void setSelectField01Flag(long flag) { setFlag("select_field_01", flag); }
	public void clearSelectField01Flag(long flag) { clearFlag("select_field_01", flag); }
	public String getSelectField01RequestParam() { return request.getParameter("_dc.select_field_01"); }
	public DialogField getSelectField01Field() { return getField("select_field_01"); }
	public DialogContext.DialogFieldState getSelectField01FieldState() { return getFieldState("select_field_01"); }
	public void addSelectField01ErrorMsg(String msg) { addErrorMessage("select_field_01", msg); }
	public String getSelectField01() { return getValue("select_field_01"); }
	public String getSelectField01(String defaultValue) { return getValue("select_field_01", defaultValue); }
	public int getSelectField01Int() { String s = getValue("select_field_01"); return s == null ? -1 : Integer.parseInt(s); }
	public int getSelectField01Int(int defaultValue) { String s = getValue("select_field_01"); return s == null ? defaultValue : Integer.parseInt(s); }
	public void setSelectField01(String value) { setValue("select_field_01", value); }
	public void setSelectField01(int value) { setValue("select_field_01", Integer.toString(value)); }

	public boolean isSelectField02ValueSet() { return hasValue("select_field_02"); }
	public boolean isSelectField02FlagSet(long flag) { return flagIsSet("select_field_02", flag); }
	public void setSelectField02Flag(long flag) { setFlag("select_field_02", flag); }
	public void clearSelectField02Flag(long flag) { clearFlag("select_field_02", flag); }
	public String getSelectField02RequestParam() { return request.getParameter("_dc.select_field_02"); }
	public DialogField getSelectField02Field() { return getField("select_field_02"); }
	public DialogContext.DialogFieldState getSelectField02FieldState() { return getFieldState("select_field_02"); }
	public void addSelectField02ErrorMsg(String msg) { addErrorMessage("select_field_02", msg); }
	public String getSelectField02() { return getValue("select_field_02"); }
	public String getSelectField02(String defaultValue) { return getValue("select_field_02", defaultValue); }
	public int getSelectField02Int() { String s = getValue("select_field_02"); return s == null ? -1 : Integer.parseInt(s); }
	public int getSelectField02Int(int defaultValue) { String s = getValue("select_field_02"); return s == null ? defaultValue : Integer.parseInt(s); }
	public void setSelectField02(String value) { setValue("select_field_02", value); }
	public void setSelectField02(int value) { setValue("select_field_02", Integer.toString(value)); }

	public boolean isSelectField03ValueSet() { return hasValue("select_field_03"); }
	public boolean isSelectField03FlagSet(long flag) { return flagIsSet("select_field_03", flag); }
	public void setSelectField03Flag(long flag) { setFlag("select_field_03", flag); }
	public void clearSelectField03Flag(long flag) { clearFlag("select_field_03", flag); }
	public String getSelectField03RequestParam() { return request.getParameter("_dc.select_field_03"); }
	public DialogField getSelectField03Field() { return getField("select_field_03"); }
	public DialogContext.DialogFieldState getSelectField03FieldState() { return getFieldState("select_field_03"); }
	public void addSelectField03ErrorMsg(String msg) { addErrorMessage("select_field_03", msg); }
	public String[] getSelectField03() { return getValues("select_field_03"); }
	public String[] getSelectField03(String[] defaultValue) { String[] o = getValues("select_field_03"); return o == null ? defaultValue : o; }
	public void setSelectField03(String[] values) { setValues("select_field_03", values); }

	public boolean isSelectField04ValueSet() { return hasValue("select_field_04"); }
	public boolean isSelectField04FlagSet(long flag) { return flagIsSet("select_field_04", flag); }
	public void setSelectField04Flag(long flag) { setFlag("select_field_04", flag); }
	public void clearSelectField04Flag(long flag) { clearFlag("select_field_04", flag); }
	public String getSelectField04RequestParam() { return request.getParameter("_dc.select_field_04"); }
	public DialogField getSelectField04Field() { return getField("select_field_04"); }
	public DialogContext.DialogFieldState getSelectField04FieldState() { return getFieldState("select_field_04"); }
	public void addSelectField04ErrorMsg(String msg) { addErrorMessage("select_field_04", msg); }
	public String[] getSelectField04() { return getValues("select_field_04"); }
	public String[] getSelectField04(String[] defaultValue) { String[] o = getValues("select_field_04"); return o == null ? defaultValue : o; }
	public void setSelectField04(String[] values) { setValues("select_field_04", values); }

}
