
/* this file is generated by com.netspective.sparx.xaf.form.Dialog.getSubclassedDialogContextCode(), do not modify (you can extend it, though) */

package dialog.context.Test;

import com.netspective.sparx.xaf.form.*;

public class DialogTest01AContext extends DialogContext
{
	public boolean isTextFieldHiddenValueSet() { return hasValue("text_field_hidden"); }
	public boolean isTextFieldHiddenFlagSet(long flag) { return flagIsSet("text_field_hidden", flag); }
	public void setTextFieldHiddenFlag(long flag) { setFlag("text_field_hidden", flag); }
	public void clearTextFieldHiddenFlag(long flag) { clearFlag("text_field_hidden", flag); }
	public String getTextFieldHiddenRequestParam() { return request.getParameter("_dc.text_field_hidden"); }
	public DialogField getTextFieldHiddenField() { return getField("text_field_hidden"); }
	public DialogContext.DialogFieldState getTextFieldHiddenFieldState() { return getFieldState("text_field_hidden"); }
	public void addTextFieldHiddenErrorMsg(String msg) { addErrorMessage("text_field_hidden", msg); }
	public String getTextFieldHidden() { return getValue("text_field_hidden"); }
	public String getTextFieldHidden(String defaultValue) { return getValue("text_field_hidden", defaultValue); }
	public String getTextFieldHiddenOrBlank() { return getValue("text_field_hidden", ""); }
	public void setTextFieldHidden(String value) { setValue("text_field_hidden", value); }

	public boolean isStaticFieldValueSet() { return hasValue("static_field"); }
	public boolean isStaticFieldFlagSet(long flag) { return flagIsSet("static_field", flag); }
	public void setStaticFieldFlag(long flag) { setFlag("static_field", flag); }
	public void clearStaticFieldFlag(long flag) { clearFlag("static_field", flag); }
	public String getStaticFieldRequestParam() { return request.getParameter("_dc.static_field"); }
	public DialogField getStaticFieldField() { return getField("static_field"); }
	public DialogContext.DialogFieldState getStaticFieldFieldState() { return getFieldState("static_field"); }
	public void addStaticFieldErrorMsg(String msg) { addErrorMessage("static_field", msg); }
	public String getStaticField() { return getValue("static_field"); }
	public String getStaticField(String defaultValue) { return getValue("static_field", defaultValue); }
	public String getStaticFieldOrBlank() { return getValue("static_field", ""); }
	public void setStaticField(String value) { setValue("static_field", value); }

	public boolean isTextFieldRequiredValueSet() { return hasValue("text_field_required"); }
	public boolean isTextFieldRequiredFlagSet(long flag) { return flagIsSet("text_field_required", flag); }
	public void setTextFieldRequiredFlag(long flag) { setFlag("text_field_required", flag); }
	public void clearTextFieldRequiredFlag(long flag) { clearFlag("text_field_required", flag); }
	public String getTextFieldRequiredRequestParam() { return request.getParameter("_dc.text_field_required"); }
	public DialogField getTextFieldRequiredField() { return getField("text_field_required"); }
	public DialogContext.DialogFieldState getTextFieldRequiredFieldState() { return getFieldState("text_field_required"); }
	public void addTextFieldRequiredErrorMsg(String msg) { addErrorMessage("text_field_required", msg); }
	public String getTextFieldRequired() { return getValue("text_field_required"); }
	public String getTextFieldRequired(String defaultValue) { return getValue("text_field_required", defaultValue); }
	public String getTextFieldRequiredOrBlank() { return getValue("text_field_required", ""); }
	public void setTextFieldRequired(String value) { setValue("text_field_required", value); }

	public boolean isTextFieldValueSet() { return hasValue("text_field"); }
	public boolean isTextFieldFlagSet(long flag) { return flagIsSet("text_field", flag); }
	public void setTextFieldFlag(long flag) { setFlag("text_field", flag); }
	public void clearTextFieldFlag(long flag) { clearFlag("text_field", flag); }
	public String getTextFieldRequestParam() { return request.getParameter("_dc.text_field"); }
	public DialogField getTextFieldField() { return getField("text_field"); }
	public DialogContext.DialogFieldState getTextFieldFieldState() { return getFieldState("text_field"); }
	public void addTextFieldErrorMsg(String msg) { addErrorMessage("text_field", msg); }
	public String getTextField() { return getValue("text_field"); }
	public String getTextField(String defaultValue) { return getValue("text_field", defaultValue); }
	public String getTextFieldOrBlank() { return getValue("text_field", ""); }
	public void setTextField(String value) { setValue("text_field", value); }

	public boolean isTextFieldEmailValueSet() { return hasValue("text_field_email"); }
	public boolean isTextFieldEmailFlagSet(long flag) { return flagIsSet("text_field_email", flag); }
	public void setTextFieldEmailFlag(long flag) { setFlag("text_field_email", flag); }
	public void clearTextFieldEmailFlag(long flag) { clearFlag("text_field_email", flag); }
	public String getTextFieldEmailRequestParam() { return request.getParameter("_dc.text_field_email"); }
	public DialogField getTextFieldEmailField() { return getField("text_field_email"); }
	public DialogContext.DialogFieldState getTextFieldEmailFieldState() { return getFieldState("text_field_email"); }
	public void addTextFieldEmailErrorMsg(String msg) { addErrorMessage("text_field_email", msg); }
	public String getTextFieldEmail() { return getValue("text_field_email"); }
	public String getTextFieldEmail(String defaultValue) { return getValue("text_field_email", defaultValue); }
	public String getTextFieldEmailOrBlank() { return getValue("text_field_email", ""); }
	public void setTextFieldEmail(String value) { setValue("text_field_email", value); }

	public boolean isEmailFieldValueSet() { return hasValue("email_field"); }
	public boolean isEmailFieldFlagSet(long flag) { return flagIsSet("email_field", flag); }
	public void setEmailFieldFlag(long flag) { setFlag("email_field", flag); }
	public void clearEmailFieldFlag(long flag) { clearFlag("email_field", flag); }
	public String getEmailFieldRequestParam() { return request.getParameter("_dc.email_field"); }
	public DialogField getEmailFieldField() { return getField("email_field"); }
	public DialogContext.DialogFieldState getEmailFieldFieldState() { return getFieldState("email_field"); }
	public void addEmailFieldErrorMsg(String msg) { addErrorMessage("email_field", msg); }
	public String getEmailField() { return getValue("email_field"); }
	public String getEmailField(String defaultValue) { return getValue("email_field", defaultValue); }
	public String getEmailFieldOrBlank() { return getValue("email_field", ""); }
	public void setEmailField(String value) { setValue("email_field", value); }

}
