
/* this file is generated by com.netspective.sparx.xaf.form.Dialog.getSubclassedDialogContextCode(), do not modify (you can extend it, though) */

package dialog.context.Test;

import com.netspective.sparx.xaf.form.*;

public class DialogTest05Context extends DialogContext
{
	public boolean isGridFieldValueSet() { return hasValue("grid_field"); }
	public boolean isGridFieldFlagSet(long flag) { return flagIsSet("grid_field", flag); }
	public void setGridFieldFlag(long flag) { setFlag("grid_field", flag); }
	public void clearGridFieldFlag(long flag) { clearFlag("grid_field", flag); }
	public String getGridFieldRequestParam() { return request.getParameter("_dc.grid_field"); }
	public DialogField getGridFieldField() { return getField("grid_field"); }
	public DialogContext.DialogFieldState getGridFieldFieldState() { return getFieldState("grid_field"); }
	public void addGridFieldErrorMsg(String msg) { addErrorMessage("grid_field", msg); }
	public boolean isGridField_compositeFieldValueSet() { return hasValue("grid_field.composite_field"); }
	public boolean isGridField_compositeFieldFlagSet(long flag) { return flagIsSet("grid_field.composite_field", flag); }
	public void setGridField_compositeFieldFlag(long flag) { setFlag("grid_field.composite_field", flag); }
	public void clearGridField_compositeFieldFlag(long flag) { clearFlag("grid_field.composite_field", flag); }
	public String getGridField_compositeFieldRequestParam() { return request.getParameter("_dc.grid_field.composite_field"); }
	public DialogField getGridField_compositeFieldField() { return getField("grid_field.composite_field"); }
	public DialogContext.DialogFieldState getGridField_compositeFieldFieldState() { return getFieldState("grid_field.composite_field"); }
	public void addGridField_compositeFieldErrorMsg(String msg) { addErrorMessage("grid_field.composite_field", msg); }
	public boolean isGridField_compositeField_integerField01ValueSet() { return hasValue("grid_field.composite_field.integer_field_01"); }
	public boolean isGridField_compositeField_integerField01FlagSet(long flag) { return flagIsSet("grid_field.composite_field.integer_field_01", flag); }
	public void setGridField_compositeField_integerField01Flag(long flag) { setFlag("grid_field.composite_field.integer_field_01", flag); }
	public void clearGridField_compositeField_integerField01Flag(long flag) { clearFlag("grid_field.composite_field.integer_field_01", flag); }
	public String getGridField_compositeField_integerField01RequestParam() { return request.getParameter("_dc.grid_field.composite_field.integer_field_01"); }
	public DialogField getGridField_compositeField_integerField01Field() { return getField("grid_field.composite_field.integer_field_01"); }
	public DialogContext.DialogFieldState getGridField_compositeField_integerField01FieldState() { return getFieldState("grid_field.composite_field.integer_field_01"); }
	public void addGridField_compositeField_integerField01ErrorMsg(String msg) { addErrorMessage("grid_field.composite_field.integer_field_01", msg); }
	public int getGridField_compositeField_integerField01() { Integer o = (Integer) getValueAsObject("grid_field.composite_field.integer_field_01"); return o == null ? 0 : o.intValue(); }
	public int getGridField_compositeField_integerField01(int defaultValue) { Integer o = (Integer) getValueAsObject("grid_field.composite_field.integer_field_01"); return o == null ? defaultValue : o.intValue(); }
	public void setGridField_compositeField_integerField01(int value) { setValue("grid_field.composite_field.integer_field_01", Integer.toString(value)); }
	public boolean isGridField_compositeField_integerField02ValueSet() { return hasValue("grid_field.composite_field.integer_field_02"); }
	public boolean isGridField_compositeField_integerField02FlagSet(long flag) { return flagIsSet("grid_field.composite_field.integer_field_02", flag); }
	public void setGridField_compositeField_integerField02Flag(long flag) { setFlag("grid_field.composite_field.integer_field_02", flag); }
	public void clearGridField_compositeField_integerField02Flag(long flag) { clearFlag("grid_field.composite_field.integer_field_02", flag); }
	public String getGridField_compositeField_integerField02RequestParam() { return request.getParameter("_dc.grid_field.composite_field.integer_field_02"); }
	public DialogField getGridField_compositeField_integerField02Field() { return getField("grid_field.composite_field.integer_field_02"); }
	public DialogContext.DialogFieldState getGridField_compositeField_integerField02FieldState() { return getFieldState("grid_field.composite_field.integer_field_02"); }
	public void addGridField_compositeField_integerField02ErrorMsg(String msg) { addErrorMessage("grid_field.composite_field.integer_field_02", msg); }
	public int getGridField_compositeField_integerField02() { Integer o = (Integer) getValueAsObject("grid_field.composite_field.integer_field_02"); return o == null ? 0 : o.intValue(); }
	public int getGridField_compositeField_integerField02(int defaultValue) { Integer o = (Integer) getValueAsObject("grid_field.composite_field.integer_field_02"); return o == null ? defaultValue : o.intValue(); }
	public void setGridField_compositeField_integerField02(int value) { setValue("grid_field.composite_field.integer_field_02", Integer.toString(value)); }
	public boolean isGridField_compositeField_integerField03ValueSet() { return hasValue("grid_field.composite_field.integer_field_03"); }
	public boolean isGridField_compositeField_integerField03FlagSet(long flag) { return flagIsSet("grid_field.composite_field.integer_field_03", flag); }
	public void setGridField_compositeField_integerField03Flag(long flag) { setFlag("grid_field.composite_field.integer_field_03", flag); }
	public void clearGridField_compositeField_integerField03Flag(long flag) { clearFlag("grid_field.composite_field.integer_field_03", flag); }
	public String getGridField_compositeField_integerField03RequestParam() { return request.getParameter("_dc.grid_field.composite_field.integer_field_03"); }
	public DialogField getGridField_compositeField_integerField03Field() { return getField("grid_field.composite_field.integer_field_03"); }
	public DialogContext.DialogFieldState getGridField_compositeField_integerField03FieldState() { return getFieldState("grid_field.composite_field.integer_field_03"); }
	public void addGridField_compositeField_integerField03ErrorMsg(String msg) { addErrorMessage("grid_field.composite_field.integer_field_03", msg); }
	public int getGridField_compositeField_integerField03() { Integer o = (Integer) getValueAsObject("grid_field.composite_field.integer_field_03"); return o == null ? 0 : o.intValue(); }
	public int getGridField_compositeField_integerField03(int defaultValue) { Integer o = (Integer) getValueAsObject("grid_field.composite_field.integer_field_03"); return o == null ? defaultValue : o.intValue(); }
	public void setGridField_compositeField_integerField03(int value) { setValue("grid_field.composite_field.integer_field_03", Integer.toString(value)); }
	public boolean isGridField_compositeField_integerField04ValueSet() { return hasValue("grid_field.composite_field.integer_field_04"); }
	public boolean isGridField_compositeField_integerField04FlagSet(long flag) { return flagIsSet("grid_field.composite_field.integer_field_04", flag); }
	public void setGridField_compositeField_integerField04Flag(long flag) { setFlag("grid_field.composite_field.integer_field_04", flag); }
	public void clearGridField_compositeField_integerField04Flag(long flag) { clearFlag("grid_field.composite_field.integer_field_04", flag); }
	public String getGridField_compositeField_integerField04RequestParam() { return request.getParameter("_dc.grid_field.composite_field.integer_field_04"); }
	public DialogField getGridField_compositeField_integerField04Field() { return getField("grid_field.composite_field.integer_field_04"); }
	public DialogContext.DialogFieldState getGridField_compositeField_integerField04FieldState() { return getFieldState("grid_field.composite_field.integer_field_04"); }
	public void addGridField_compositeField_integerField04ErrorMsg(String msg) { addErrorMessage("grid_field.composite_field.integer_field_04", msg); }
	public int getGridField_compositeField_integerField04() { Integer o = (Integer) getValueAsObject("grid_field.composite_field.integer_field_04"); return o == null ? 0 : o.intValue(); }
	public int getGridField_compositeField_integerField04(int defaultValue) { Integer o = (Integer) getValueAsObject("grid_field.composite_field.integer_field_04"); return o == null ? defaultValue : o.intValue(); }
	public void setGridField_compositeField_integerField04(int value) { setValue("grid_field.composite_field.integer_field_04", Integer.toString(value)); }

	public boolean isStaticField02ValueSet() { return hasValue("static_field_02"); }
	public boolean isStaticField02FlagSet(long flag) { return flagIsSet("static_field_02", flag); }
	public void setStaticField02Flag(long flag) { setFlag("static_field_02", flag); }
	public void clearStaticField02Flag(long flag) { clearFlag("static_field_02", flag); }
	public String getStaticField02RequestParam() { return request.getParameter("_dc.static_field_02"); }
	public DialogField getStaticField02Field() { return getField("static_field_02"); }
	public DialogContext.DialogFieldState getStaticField02FieldState() { return getFieldState("static_field_02"); }
	public void addStaticField02ErrorMsg(String msg) { addErrorMessage("static_field_02", msg); }
	public String getStaticField02() { return getValue("static_field_02"); }
	public String getStaticField02(String defaultValue) { return getValue("static_field_02", defaultValue); }
	public String getStaticField02OrBlank() { return getValue("static_field_02", ""); }
	public void setStaticField02(String value) { setValue("static_field_02", value); }

}
