
/* this file is generated by com.netspective.sparx.xaf.form.Dialog.getSubclassedDialogContextCode(), do not modify (you can extend it, though) */

package dialog.context.Test;

import com.netspective.sparx.xaf.form.*;

public class DialogTest07Context extends DialogContext
{
	public boolean isSelFieldListValueSet() { return hasValue("sel_field_list"); }
	public boolean isSelFieldListFlagSet(long flag) { return flagIsSet("sel_field_list", flag); }
	public void setSelFieldListFlag(long flag) { setFlag("sel_field_list", flag); }
	public void clearSelFieldListFlag(long flag) { clearFlag("sel_field_list", flag); }
	public String getSelFieldListRequestParam() { return request.getParameter("_dc.sel_field_list"); }
	public DialogField getSelFieldListField() { return getField("sel_field_list"); }
	public DialogContext.DialogFieldState getSelFieldListFieldState() { return getFieldState("sel_field_list"); }
	public void addSelFieldListErrorMsg(String msg) { addErrorMessage("sel_field_list", msg); }
	public String getSelFieldList() { return getValue("sel_field_list"); }
	public String getSelFieldList(String defaultValue) { return getValue("sel_field_list", defaultValue); }
	public String getSelFieldListOrBlank() { return getValue("sel_field_list", ""); }
	public void setSelFieldList(String value) { setValue("sel_field_list", value); }

	public boolean isTextFieldValueSet() { return hasValue("text_field"); }
	public boolean isTextFieldFlagSet(long flag) { return flagIsSet("text_field", flag); }
	public void setTextFieldFlag(long flag) { setFlag("text_field", flag); }
	public void clearTextFieldFlag(long flag) { clearFlag("text_field", flag); }
	public String getTextFieldRequestParam() { return request.getParameter("_dc.text_field"); }
	public DialogField getTextFieldField() { return getField("text_field"); }
	public DialogContext.DialogFieldState getTextFieldFieldState() { return getFieldState("text_field"); }
	public void addTextFieldErrorMsg(String msg) { addErrorMessage("text_field", msg); }
	public String getTextField() { return getValue("text_field"); }
	public String getTextField(String defaultValue) { return getValue("text_field", defaultValue); }
	public String getTextFieldOrBlank() { return getValue("text_field", ""); }
	public void setTextField(String value) { setValue("text_field", value); }

}
