
/* this file is generated by com.netspective.sparx.xaf.form.Dialog.getSubclassedDialogContextCode(), do not modify (you can extend it, though) */

package dialog.context.Test;

import com.netspective.sparx.xaf.form.*;

public class DialogTest15Context extends DialogContext
{
	public boolean isTextFieldHiddenValueSet() { return hasValue("text_field_hidden"); }
	public boolean isTextFieldHiddenFlagSet(long flag) { return flagIsSet("text_field_hidden", flag); }
	public void setTextFieldHiddenFlag(long flag) { setFlag("text_field_hidden", flag); }
	public void clearTextFieldHiddenFlag(long flag) { clearFlag("text_field_hidden", flag); }
	public String getTextFieldHiddenRequestParam() { return request.getParameter("_dc.text_field_hidden"); }
	public DialogField getTextFieldHiddenField() { return getField("text_field_hidden"); }
	public DialogContext.DialogFieldState getTextFieldHiddenFieldState() { return getFieldState("text_field_hidden"); }
	public void addTextFieldHiddenErrorMsg(String msg) { addErrorMessage("text_field_hidden", msg); }
	public String getTextFieldHidden() { return getValue("text_field_hidden"); }
	public String getTextFieldHidden(String defaultValue) { return getValue("text_field_hidden", defaultValue); }
	public String getTextFieldHiddenOrBlank() { return getValue("text_field_hidden", ""); }
	public void setTextFieldHidden(String value) { setValue("text_field_hidden", value); }

	public boolean isStaticFieldValueSet() { return hasValue("static_field"); }
	public boolean isStaticFieldFlagSet(long flag) { return flagIsSet("static_field", flag); }
	public void setStaticFieldFlag(long flag) { setFlag("static_field", flag); }
	public void clearStaticFieldFlag(long flag) { clearFlag("static_field", flag); }
	public String getStaticFieldRequestParam() { return request.getParameter("_dc.static_field"); }
	public DialogField getStaticFieldField() { return getField("static_field"); }
	public DialogContext.DialogFieldState getStaticFieldFieldState() { return getFieldState("static_field"); }
	public void addStaticFieldErrorMsg(String msg) { addErrorMessage("static_field", msg); }
	public String getStaticField() { return getValue("static_field"); }
	public String getStaticField(String defaultValue) { return getValue("static_field", defaultValue); }
	public String getStaticFieldOrBlank() { return getValue("static_field", ""); }
	public void setStaticField(String value) { setValue("static_field", value); }

	public boolean isTextFieldRequiredValueSet() { return hasValue("text_field_required"); }
	public boolean isTextFieldRequiredFlagSet(long flag) { return flagIsSet("text_field_required", flag); }
	public void setTextFieldRequiredFlag(long flag) { setFlag("text_field_required", flag); }
	public void clearTextFieldRequiredFlag(long flag) { clearFlag("text_field_required", flag); }
	public String getTextFieldRequiredRequestParam() { return request.getParameter("_dc.text_field_required"); }
	public DialogField getTextFieldRequiredField() { return getField("text_field_required"); }
	public DialogContext.DialogFieldState getTextFieldRequiredFieldState() { return getFieldState("text_field_required"); }
	public void addTextFieldRequiredErrorMsg(String msg) { addErrorMessage("text_field_required", msg); }
	public String getTextFieldRequired() { return getValue("text_field_required"); }
	public String getTextFieldRequired(String defaultValue) { return getValue("text_field_required", defaultValue); }
	public String getTextFieldRequiredOrBlank() { return getValue("text_field_required", ""); }
	public void setTextFieldRequired(String value) { setValue("text_field_required", value); }

	public boolean isTextFieldValueSet() { return hasValue("text_field"); }
	public boolean isTextFieldFlagSet(long flag) { return flagIsSet("text_field", flag); }
	public void setTextFieldFlag(long flag) { setFlag("text_field", flag); }
	public void clearTextFieldFlag(long flag) { clearFlag("text_field", flag); }
	public String getTextFieldRequestParam() { return request.getParameter("_dc.text_field"); }
	public DialogField getTextFieldField() { return getField("text_field"); }
	public DialogContext.DialogFieldState getTextFieldFieldState() { return getFieldState("text_field"); }
	public void addTextFieldErrorMsg(String msg) { addErrorMessage("text_field", msg); }
	public String getTextField() { return getValue("text_field"); }
	public String getTextField(String defaultValue) { return getValue("text_field", defaultValue); }
	public String getTextFieldOrBlank() { return getValue("text_field", ""); }
	public void setTextField(String value) { setValue("text_field", value); }

	public boolean isTextFieldEmailValueSet() { return hasValue("text_field_email"); }
	public boolean isTextFieldEmailFlagSet(long flag) { return flagIsSet("text_field_email", flag); }
	public void setTextFieldEmailFlag(long flag) { setFlag("text_field_email", flag); }
	public void clearTextFieldEmailFlag(long flag) { clearFlag("text_field_email", flag); }
	public String getTextFieldEmailRequestParam() { return request.getParameter("_dc.text_field_email"); }
	public DialogField getTextFieldEmailField() { return getField("text_field_email"); }
	public DialogContext.DialogFieldState getTextFieldEmailFieldState() { return getFieldState("text_field_email"); }
	public void addTextFieldEmailErrorMsg(String msg) { addErrorMessage("text_field_email", msg); }
	public String getTextFieldEmail() { return getValue("text_field_email"); }
	public String getTextFieldEmail(String defaultValue) { return getValue("text_field_email", defaultValue); }
	public String getTextFieldEmailOrBlank() { return getValue("text_field_email", ""); }
	public void setTextFieldEmail(String value) { setValue("text_field_email", value); }

	public boolean isEmailFieldValueSet() { return hasValue("email_field"); }
	public boolean isEmailFieldFlagSet(long flag) { return flagIsSet("email_field", flag); }
	public void setEmailFieldFlag(long flag) { setFlag("email_field", flag); }
	public void clearEmailFieldFlag(long flag) { clearFlag("email_field", flag); }
	public String getEmailFieldRequestParam() { return request.getParameter("_dc.email_field"); }
	public DialogField getEmailFieldField() { return getField("email_field"); }
	public DialogContext.DialogFieldState getEmailFieldFieldState() { return getFieldState("email_field"); }
	public void addEmailFieldErrorMsg(String msg) { addErrorMessage("email_field", msg); }
	public String getEmailField() { return getValue("email_field"); }
	public String getEmailField(String defaultValue) { return getValue("email_field", defaultValue); }
	public String getEmailFieldOrBlank() { return getValue("email_field", ""); }
	public void setEmailField(String value) { setValue("email_field", value); }

	public boolean isIntegerFieldValueSet() { return hasValue("integer_field"); }
	public boolean isIntegerFieldFlagSet(long flag) { return flagIsSet("integer_field", flag); }
	public void setIntegerFieldFlag(long flag) { setFlag("integer_field", flag); }
	public void clearIntegerFieldFlag(long flag) { clearFlag("integer_field", flag); }
	public String getIntegerFieldRequestParam() { return request.getParameter("_dc.integer_field"); }
	public DialogField getIntegerFieldField() { return getField("integer_field"); }
	public DialogContext.DialogFieldState getIntegerFieldFieldState() { return getFieldState("integer_field"); }
	public void addIntegerFieldErrorMsg(String msg) { addErrorMessage("integer_field", msg); }
	public int getIntegerField() { Integer o = (Integer) getValueAsObject("integer_field"); return o == null ? 0 : o.intValue(); }
	public int getIntegerField(int defaultValue) { Integer o = (Integer) getValueAsObject("integer_field"); return o == null ? defaultValue : o.intValue(); }
	public void setIntegerField(int value) { setValue("integer_field", Integer.toString(value)); }

	public boolean isFloatFieldValueSet() { return hasValue("float_field"); }
	public boolean isFloatFieldFlagSet(long flag) { return flagIsSet("float_field", flag); }
	public void setFloatFieldFlag(long flag) { setFlag("float_field", flag); }
	public void clearFloatFieldFlag(long flag) { clearFlag("float_field", flag); }
	public String getFloatFieldRequestParam() { return request.getParameter("_dc.float_field"); }
	public DialogField getFloatFieldField() { return getField("float_field"); }
	public DialogContext.DialogFieldState getFloatFieldFieldState() { return getFieldState("float_field"); }
	public void addFloatFieldErrorMsg(String msg) { addErrorMessage("float_field", msg); }
	public float getFloatField() { Float o = (Float) getValueAsObject("float_field"); return o == null ? (float) 0.0 : o.floatValue(); }
	public float getFloatField(float defaultValue) { Float o = (Float) getValueAsObject("float_field"); return o == null ? defaultValue : o.floatValue(); }
	public void setFloatField(float value) { setValue("float_field", Float.toString(value)); }

	public boolean isCurrencyFieldValueSet() { return hasValue("currency_field"); }
	public boolean isCurrencyFieldFlagSet(long flag) { return flagIsSet("currency_field", flag); }
	public void setCurrencyFieldFlag(long flag) { setFlag("currency_field", flag); }
	public void clearCurrencyFieldFlag(long flag) { clearFlag("currency_field", flag); }
	public String getCurrencyFieldRequestParam() { return request.getParameter("_dc.currency_field"); }
	public DialogField getCurrencyFieldField() { return getField("currency_field"); }
	public DialogContext.DialogFieldState getCurrencyFieldFieldState() { return getFieldState("currency_field"); }
	public void addCurrencyFieldErrorMsg(String msg) { addErrorMessage("currency_field", msg); }
	public String getCurrencyField() { return getValue("currency_field"); }
	public String getCurrencyField(String defaultValue) { return getValue("currency_field", defaultValue); }
	public String getCurrencyFieldOrBlank() { return getValue("currency_field", ""); }
	public void setCurrencyField(String value) { setValue("currency_field", value); }

	public boolean isPhoneField1ValueSet() { return hasValue("phone_field1"); }
	public boolean isPhoneField1FlagSet(long flag) { return flagIsSet("phone_field1", flag); }
	public void setPhoneField1Flag(long flag) { setFlag("phone_field1", flag); }
	public void clearPhoneField1Flag(long flag) { clearFlag("phone_field1", flag); }
	public String getPhoneField1RequestParam() { return request.getParameter("_dc.phone_field1"); }
	public DialogField getPhoneField1Field() { return getField("phone_field1"); }
	public DialogContext.DialogFieldState getPhoneField1FieldState() { return getFieldState("phone_field1"); }
	public void addPhoneField1ErrorMsg(String msg) { addErrorMessage("phone_field1", msg); }
	public String getPhoneField1() { return getValue("phone_field1"); }
	public String getPhoneField1(String defaultValue) { return getValue("phone_field1", defaultValue); }
	public String getPhoneField1OrBlank() { return getValue("phone_field1", ""); }
	public void setPhoneField1(String value) { setValue("phone_field1", value); }

	public boolean isPhoneField2ValueSet() { return hasValue("phone_field2"); }
	public boolean isPhoneField2FlagSet(long flag) { return flagIsSet("phone_field2", flag); }
	public void setPhoneField2Flag(long flag) { setFlag("phone_field2", flag); }
	public void clearPhoneField2Flag(long flag) { clearFlag("phone_field2", flag); }
	public String getPhoneField2RequestParam() { return request.getParameter("_dc.phone_field2"); }
	public DialogField getPhoneField2Field() { return getField("phone_field2"); }
	public DialogContext.DialogFieldState getPhoneField2FieldState() { return getFieldState("phone_field2"); }
	public void addPhoneField2ErrorMsg(String msg) { addErrorMessage("phone_field2", msg); }
	public String getPhoneField2() { return getValue("phone_field2"); }
	public String getPhoneField2(String defaultValue) { return getValue("phone_field2", defaultValue); }
	public String getPhoneField2OrBlank() { return getValue("phone_field2", ""); }
	public void setPhoneField2(String value) { setValue("phone_field2", value); }

	public boolean isZipFieldValueSet() { return hasValue("zip_field"); }
	public boolean isZipFieldFlagSet(long flag) { return flagIsSet("zip_field", flag); }
	public void setZipFieldFlag(long flag) { setFlag("zip_field", flag); }
	public void clearZipFieldFlag(long flag) { clearFlag("zip_field", flag); }
	public String getZipFieldRequestParam() { return request.getParameter("_dc.zip_field"); }
	public DialogField getZipFieldField() { return getField("zip_field"); }
	public DialogContext.DialogFieldState getZipFieldFieldState() { return getFieldState("zip_field"); }
	public void addZipFieldErrorMsg(String msg) { addErrorMessage("zip_field", msg); }
	public String getZipField() { return getValue("zip_field"); }
	public String getZipField(String defaultValue) { return getValue("zip_field", defaultValue); }
	public String getZipFieldOrBlank() { return getValue("zip_field", ""); }
	public void setZipField(String value) { setValue("zip_field", value); }

	public boolean isSsnFieldValueSet() { return hasValue("ssn_field"); }
	public boolean isSsnFieldFlagSet(long flag) { return flagIsSet("ssn_field", flag); }
	public void setSsnFieldFlag(long flag) { setFlag("ssn_field", flag); }
	public void clearSsnFieldFlag(long flag) { clearFlag("ssn_field", flag); }
	public String getSsnFieldRequestParam() { return request.getParameter("_dc.ssn_field"); }
	public DialogField getSsnFieldField() { return getField("ssn_field"); }
	public DialogContext.DialogFieldState getSsnFieldFieldState() { return getFieldState("ssn_field"); }
	public void addSsnFieldErrorMsg(String msg) { addErrorMessage("ssn_field", msg); }
	public String getSsnField() { return getValue("ssn_field"); }
	public String getSsnField(String defaultValue) { return getValue("ssn_field", defaultValue); }
	public String getSsnFieldOrBlank() { return getValue("ssn_field", ""); }
	public void setSsnField(String value) { setValue("ssn_field", value); }

}
