
/* this file is generated by com.netspective.sparx.xaf.form.Dialog.getSubclassedDialogContextCode(), do not modify (you can extend it, though) */

package dialog.context.Test;

import java.util.Date;
import com.netspective.sparx.xaf.form.*;

public class DialogTest02Context extends DialogContext
{
	public boolean isMemoField01ValueSet() { return hasValue("memo_field_01"); }
	public boolean isMemoField01FlagSet(long flag) { return flagIsSet("memo_field_01", flag); }
	public void setMemoField01Flag(long flag) { setFlag("memo_field_01", flag); }
	public void clearMemoField01Flag(long flag) { clearFlag("memo_field_01", flag); }
	public String getMemoField01RequestParam() { return request.getParameter("_dc.memo_field_01"); }
	public DialogField getMemoField01Field() { return getField("memo_field_01"); }
	public DialogContext.DialogFieldState getMemoField01FieldState() { return getFieldState("memo_field_01"); }
	public void addMemoField01ErrorMsg(String msg) { addErrorMessage("memo_field_01", msg); }
	public String getMemoField01() { return getValue("memo_field_01"); }
	public String getMemoField01(String defaultValue) { return getValue("memo_field_01", defaultValue); }
	public String getMemoField01OrBlank() { return getValue("memo_field_01", ""); }
	public void setMemoField01(String value) { setValue("memo_field_01", value); }

	public boolean isDurationValueSet() { return hasValue("duration"); }
	public boolean isDurationFlagSet(long flag) { return flagIsSet("duration", flag); }
	public void setDurationFlag(long flag) { setFlag("duration", flag); }
	public void clearDurationFlag(long flag) { clearFlag("duration", flag); }
	public String getDurationRequestParam() { return request.getParameter("_dc.duration"); }
	public DialogField getDurationField() { return getField("duration"); }
	public DialogContext.DialogFieldState getDurationFieldState() { return getFieldState("duration"); }
	public void addDurationErrorMsg(String msg) { addErrorMessage("duration", msg); }
	public boolean isDuration_durationBeginValueSet() { return hasValue("duration.duration_begin"); }
	public boolean isDuration_durationBeginFlagSet(long flag) { return flagIsSet("duration.duration_begin", flag); }
	public void setDuration_durationBeginFlag(long flag) { setFlag("duration.duration_begin", flag); }
	public void clearDuration_durationBeginFlag(long flag) { clearFlag("duration.duration_begin", flag); }
	public String getDuration_durationBeginRequestParam() { return request.getParameter("_dc.duration.duration_begin"); }
	public DialogField getDuration_durationBeginField() { return getField("duration.duration_begin"); }
	public DialogContext.DialogFieldState getDuration_durationBeginFieldState() { return getFieldState("duration.duration_begin"); }
	public void addDuration_durationBeginErrorMsg(String msg) { addErrorMessage("duration.duration_begin", msg); }
	public Date getDuration_durationBegin() { return (Date) getValueAsObject("duration.duration_begin"); }
	public Date getDuration_durationBegin(Date defaultValue) { return (Date) getValueAsObject("duration.duration_begin", defaultValue); }
	public void setDuration_durationBegin(String value) { setValue("duration.duration_begin", value); }
	public boolean isDuration_durationEndValueSet() { return hasValue("duration.duration_end"); }
	public boolean isDuration_durationEndFlagSet(long flag) { return flagIsSet("duration.duration_end", flag); }
	public void setDuration_durationEndFlag(long flag) { setFlag("duration.duration_end", flag); }
	public void clearDuration_durationEndFlag(long flag) { clearFlag("duration.duration_end", flag); }
	public String getDuration_durationEndRequestParam() { return request.getParameter("_dc.duration.duration_end"); }
	public DialogField getDuration_durationEndField() { return getField("duration.duration_end"); }
	public DialogContext.DialogFieldState getDuration_durationEndFieldState() { return getFieldState("duration.duration_end"); }
	public void addDuration_durationEndErrorMsg(String msg) { addErrorMessage("duration.duration_end", msg); }
	public Date getDuration_durationEnd() { return (Date) getValueAsObject("duration.duration_end"); }
	public Date getDuration_durationEnd(Date defaultValue) { return (Date) getValueAsObject("duration.duration_end", defaultValue); }
	public void setDuration_durationEnd(String value) { setValue("duration.duration_end", value); }

	public boolean isDateFieldStrictValueSet() { return hasValue("date_field_strict"); }
	public boolean isDateFieldStrictFlagSet(long flag) { return flagIsSet("date_field_strict", flag); }
	public void setDateFieldStrictFlag(long flag) { setFlag("date_field_strict", flag); }
	public void clearDateFieldStrictFlag(long flag) { clearFlag("date_field_strict", flag); }
	public String getDateFieldStrictRequestParam() { return request.getParameter("_dc.date_field_strict"); }
	public DialogField getDateFieldStrictField() { return getField("date_field_strict"); }
	public DialogContext.DialogFieldState getDateFieldStrictFieldState() { return getFieldState("date_field_strict"); }
	public void addDateFieldStrictErrorMsg(String msg) { addErrorMessage("date_field_strict", msg); }
	public Date getDateFieldStrict() { return (Date) getValueAsObject("date_field_strict"); }
	public Date getDateFieldStrict(Date defaultValue) { return (Date) getValueAsObject("date_field_strict", defaultValue); }
	public void setDateFieldStrict(String value) { setValue("date_field_strict", value); }

	public boolean isDateFieldNonstrictValueSet() { return hasValue("date_field_nonstrict"); }
	public boolean isDateFieldNonstrictFlagSet(long flag) { return flagIsSet("date_field_nonstrict", flag); }
	public void setDateFieldNonstrictFlag(long flag) { setFlag("date_field_nonstrict", flag); }
	public void clearDateFieldNonstrictFlag(long flag) { clearFlag("date_field_nonstrict", flag); }
	public String getDateFieldNonstrictRequestParam() { return request.getParameter("_dc.date_field_nonstrict"); }
	public DialogField getDateFieldNonstrictField() { return getField("date_field_nonstrict"); }
	public DialogContext.DialogFieldState getDateFieldNonstrictFieldState() { return getFieldState("date_field_nonstrict"); }
	public void addDateFieldNonstrictErrorMsg(String msg) { addErrorMessage("date_field_nonstrict", msg); }
	public Date getDateFieldNonstrict() { return (Date) getValueAsObject("date_field_nonstrict"); }
	public Date getDateFieldNonstrict(Date defaultValue) { return (Date) getValueAsObject("date_field_nonstrict", defaultValue); }
	public void setDateFieldNonstrict(String value) { setValue("date_field_nonstrict", value); }

	public boolean isTimeFieldValueSet() { return hasValue("time_field"); }
	public boolean isTimeFieldFlagSet(long flag) { return flagIsSet("time_field", flag); }
	public void setTimeFieldFlag(long flag) { setFlag("time_field", flag); }
	public void clearTimeFieldFlag(long flag) { clearFlag("time_field", flag); }
	public String getTimeFieldRequestParam() { return request.getParameter("_dc.time_field"); }
	public DialogField getTimeFieldField() { return getField("time_field"); }
	public DialogContext.DialogFieldState getTimeFieldFieldState() { return getFieldState("time_field"); }
	public void addTimeFieldErrorMsg(String msg) { addErrorMessage("time_field", msg); }
	public Date getTimeField() { return (Date) getValueAsObject("time_field"); }
	public Date getTimeField(Date defaultValue) { return (Date) getValueAsObject("time_field", defaultValue); }
	public void setTimeField(String value) { setValue("time_field", value); }

	public boolean isBoolFieldRadioValueSet() { return hasValue("bool_field_radio"); }
	public boolean isBoolFieldRadioFlagSet(long flag) { return flagIsSet("bool_field_radio", flag); }
	public void setBoolFieldRadioFlag(long flag) { setFlag("bool_field_radio", flag); }
	public void clearBoolFieldRadioFlag(long flag) { clearFlag("bool_field_radio", flag); }
	public String getBoolFieldRadioRequestParam() { return request.getParameter("_dc.bool_field_radio"); }
	public DialogField getBoolFieldRadioField() { return getField("bool_field_radio"); }
	public DialogContext.DialogFieldState getBoolFieldRadioFieldState() { return getFieldState("bool_field_radio"); }
	public void addBoolFieldRadioErrorMsg(String msg) { addErrorMessage("bool_field_radio", msg); }
	public boolean getBoolFieldRadio() { Boolean o = (Boolean) getValueAsObject("bool_field_radio"); return o == null ? false : o.booleanValue(); }
	public boolean getBoolFieldRadio(boolean defaultValue) { Boolean o = (Boolean) getValueAsObject("bool_field_radio"); return o == null ? defaultValue : o.booleanValue(); }
	public void setBoolFieldRadio(boolean value) { setValue("bool_field_radio", value == true ? "1" : "0"); }

	public boolean isBoolFieldAloneValueSet() { return hasValue("bool_field_alone"); }
	public boolean isBoolFieldAloneFlagSet(long flag) { return flagIsSet("bool_field_alone", flag); }
	public void setBoolFieldAloneFlag(long flag) { setFlag("bool_field_alone", flag); }
	public void clearBoolFieldAloneFlag(long flag) { clearFlag("bool_field_alone", flag); }
	public String getBoolFieldAloneRequestParam() { return request.getParameter("_dc.bool_field_alone"); }
	public DialogField getBoolFieldAloneField() { return getField("bool_field_alone"); }
	public DialogContext.DialogFieldState getBoolFieldAloneFieldState() { return getFieldState("bool_field_alone"); }
	public void addBoolFieldAloneErrorMsg(String msg) { addErrorMessage("bool_field_alone", msg); }
	public boolean getBoolFieldAlone() { Boolean o = (Boolean) getValueAsObject("bool_field_alone"); return o == null ? false : o.booleanValue(); }
	public boolean getBoolFieldAlone(boolean defaultValue) { Boolean o = (Boolean) getValueAsObject("bool_field_alone"); return o == null ? defaultValue : o.booleanValue(); }
	public void setBoolFieldAlone(boolean value) { setValue("bool_field_alone", value == true ? "1" : "0"); }

	public boolean isBoolFieldComboValueSet() { return hasValue("bool_field_combo"); }
	public boolean isBoolFieldComboFlagSet(long flag) { return flagIsSet("bool_field_combo", flag); }
	public void setBoolFieldComboFlag(long flag) { setFlag("bool_field_combo", flag); }
	public void clearBoolFieldComboFlag(long flag) { clearFlag("bool_field_combo", flag); }
	public String getBoolFieldComboRequestParam() { return request.getParameter("_dc.bool_field_combo"); }
	public DialogField getBoolFieldComboField() { return getField("bool_field_combo"); }
	public DialogContext.DialogFieldState getBoolFieldComboFieldState() { return getFieldState("bool_field_combo"); }
	public void addBoolFieldComboErrorMsg(String msg) { addErrorMessage("bool_field_combo", msg); }
	public boolean getBoolFieldCombo() { Boolean o = (Boolean) getValueAsObject("bool_field_combo"); return o == null ? false : o.booleanValue(); }
	public boolean getBoolFieldCombo(boolean defaultValue) { Boolean o = (Boolean) getValueAsObject("bool_field_combo"); return o == null ? defaultValue : o.booleanValue(); }
	public void setBoolFieldCombo(boolean value) { setValue("bool_field_combo", value == true ? "1" : "0"); }

}
