
/* this file is generated by com.netspective.sparx.xaf.form.Dialog.getSubclassedDialogContextCode(), do not modify (you can extend it, though) */

package dialog.context.Test;

import com.netspective.sparx.xaf.form.*;

public class DialogTest09Context extends DialogContext
{
	public boolean isStaticFieldValueSet() { return hasValue("static_field"); }
	public boolean isStaticFieldFlagSet(long flag) { return flagIsSet("static_field", flag); }
	public void setStaticFieldFlag(long flag) { setFlag("static_field", flag); }
	public void clearStaticFieldFlag(long flag) { clearFlag("static_field", flag); }
	public String getStaticFieldRequestParam() { return request.getParameter("_dc.static_field"); }
	public DialogField getStaticFieldField() { return getField("static_field"); }
	public DialogContext.DialogFieldState getStaticFieldFieldState() { return getFieldState("static_field"); }
	public void addStaticFieldErrorMsg(String msg) { addErrorMessage("static_field", msg); }
	public String getStaticField() { return getValue("static_field"); }
	public String getStaticField(String defaultValue) { return getValue("static_field", defaultValue); }
	public String getStaticFieldOrBlank() { return getValue("static_field", ""); }
	public void setStaticField(String value) { setValue("static_field", value); }

	public boolean isTextFieldValueSet() { return hasValue("text_field"); }
	public boolean isTextFieldFlagSet(long flag) { return flagIsSet("text_field", flag); }
	public void setTextFieldFlag(long flag) { setFlag("text_field", flag); }
	public void clearTextFieldFlag(long flag) { clearFlag("text_field", flag); }
	public String getTextFieldRequestParam() { return request.getParameter("_dc.text_field"); }
	public DialogField getTextFieldField() { return getField("text_field"); }
	public DialogContext.DialogFieldState getTextFieldFieldState() { return getFieldState("text_field"); }
	public void addTextFieldErrorMsg(String msg) { addErrorMessage("text_field", msg); }
	public String getTextField() { return getValue("text_field"); }
	public String getTextField(String defaultValue) { return getValue("text_field", defaultValue); }
	public String getTextFieldOrBlank() { return getValue("text_field", ""); }
	public void setTextField(String value) { setValue("text_field", value); }

	public boolean isSelectFieldValueSet() { return hasValue("select_field"); }
	public boolean isSelectFieldFlagSet(long flag) { return flagIsSet("select_field", flag); }
	public void setSelectFieldFlag(long flag) { setFlag("select_field", flag); }
	public void clearSelectFieldFlag(long flag) { clearFlag("select_field", flag); }
	public String getSelectFieldRequestParam() { return request.getParameter("_dc.select_field"); }
	public DialogField getSelectFieldField() { return getField("select_field"); }
	public DialogContext.DialogFieldState getSelectFieldFieldState() { return getFieldState("select_field"); }
	public void addSelectFieldErrorMsg(String msg) { addErrorMessage("select_field", msg); }
	public String getSelectField() { return getValue("select_field"); }
	public String getSelectField(String defaultValue) { return getValue("select_field", defaultValue); }
	public int getSelectFieldInt() { String s = getValue("select_field"); return s == null ? -1 : Integer.parseInt(s); }
	public int getSelectFieldInt(int defaultValue) { String s = getValue("select_field"); return s == null ? defaultValue : Integer.parseInt(s); }
	public void setSelectField(String value) { setValue("select_field", value); }
	public void setSelectField(int value) { setValue("select_field", Integer.toString(value)); }

	public boolean isTextFieldHiddenValueSet() { return hasValue("text_field_hidden"); }
	public boolean isTextFieldHiddenFlagSet(long flag) { return flagIsSet("text_field_hidden", flag); }
	public void setTextFieldHiddenFlag(long flag) { setFlag("text_field_hidden", flag); }
	public void clearTextFieldHiddenFlag(long flag) { clearFlag("text_field_hidden", flag); }
	public String getTextFieldHiddenRequestParam() { return request.getParameter("_dc.text_field_hidden"); }
	public DialogField getTextFieldHiddenField() { return getField("text_field_hidden"); }
	public DialogContext.DialogFieldState getTextFieldHiddenFieldState() { return getFieldState("text_field_hidden"); }
	public void addTextFieldHiddenErrorMsg(String msg) { addErrorMessage("text_field_hidden", msg); }
	public String getTextFieldHidden() { return getValue("text_field_hidden"); }
	public String getTextFieldHidden(String defaultValue) { return getValue("text_field_hidden", defaultValue); }
	public String getTextFieldHiddenOrBlank() { return getValue("text_field_hidden", ""); }
	public void setTextFieldHidden(String value) { setValue("text_field_hidden", value); }

	public boolean isSelectFieldHiddenValueSet() { return hasValue("select_field_hidden"); }
	public boolean isSelectFieldHiddenFlagSet(long flag) { return flagIsSet("select_field_hidden", flag); }
	public void setSelectFieldHiddenFlag(long flag) { setFlag("select_field_hidden", flag); }
	public void clearSelectFieldHiddenFlag(long flag) { clearFlag("select_field_hidden", flag); }
	public String getSelectFieldHiddenRequestParam() { return request.getParameter("_dc.select_field_hidden"); }
	public DialogField getSelectFieldHiddenField() { return getField("select_field_hidden"); }
	public DialogContext.DialogFieldState getSelectFieldHiddenFieldState() { return getFieldState("select_field_hidden"); }
	public void addSelectFieldHiddenErrorMsg(String msg) { addErrorMessage("select_field_hidden", msg); }
	public String getSelectFieldHidden() { return getValue("select_field_hidden"); }
	public String getSelectFieldHidden(String defaultValue) { return getValue("select_field_hidden", defaultValue); }
	public int getSelectFieldHiddenInt() { String s = getValue("select_field_hidden"); return s == null ? -1 : Integer.parseInt(s); }
	public int getSelectFieldHiddenInt(int defaultValue) { String s = getValue("select_field_hidden"); return s == null ? defaultValue : Integer.parseInt(s); }
	public void setSelectFieldHidden(String value) { setValue("select_field_hidden", value); }
	public void setSelectFieldHidden(int value) { setValue("select_field_hidden", Integer.toString(value)); }

}
