
/* this file is generated by com.netspective.sparx.util.xml.XmlSource.createNodeIdentifiersClass(), do not modify (you can extend it, though) */

package id;

public class ACL
{
    static public final String APP = "/app";
    static public final String APP_ORDERS = "/app/orders";
    static public final String APP_ORDERS_CREATE_ORDER = "/app/orders/create_order";
    static public final String APP_ORDERS_DELETE_ORDER = "/app/orders/delete_order";
    static public final String APP_ORDERS_EDIT_ORDER = "/app/orders/edit_order";
    static public final String APP_ORDERS_ORDER_LIST = "/app/orders/order_list";
    static public final String APP_ORDERS_VIEW_ORDER = "/app/orders/view_order";
    static public final String ROLE = "/role";
    static public final String ROLE_NORMAL_USER = "/role/normal-user";
    static public final String ROLE_SUPER_USER = "/role/super-user";
}
