
/* this file is generated by com.netspective.sparx.xaf.form.Dialog.getSubclassedDialogContextCode(), do not modify (you can extend it, though) */

package dialog.context.main;

import com.netspective.sparx.xaf.form.*;

public class PatientEntryContext extends DialogContext
{
	public boolean isFirstNameValueSet() { return hasValue("first_name"); }
	public boolean isFirstNameFlagSet(long flag) { return flagIsSet("first_name", flag); }
	public void setFirstNameFlag(long flag) { setFlag("first_name", flag); }
	public void clearFirstNameFlag(long flag) { clearFlag("first_name", flag); }
	public String getFirstNameRequestParam() { return request.getParameter("_dc.first_name"); }
	public DialogField getFirstNameField() { return getField("first_name"); }
	public DialogContext.DialogFieldState getFirstNameFieldState() { return getFieldState("first_name"); }
	public void addFirstNameErrorMsg(String msg) { addErrorMessage("first_name", msg); }
	public String getFirstName() { return getValue("first_name"); }
	public String getFirstName(String defaultValue) { return getValue("first_name", defaultValue); }
	public String getFirstNameOrBlank() { return getValue("first_name", ""); }
	public void setFirstName(String value) { setValue("first_name", value); }

	public boolean isLastNameValueSet() { return hasValue("last_name"); }
	public boolean isLastNameFlagSet(long flag) { return flagIsSet("last_name", flag); }
	public void setLastNameFlag(long flag) { setFlag("last_name", flag); }
	public void clearLastNameFlag(long flag) { clearFlag("last_name", flag); }
	public String getLastNameRequestParam() { return request.getParameter("_dc.last_name"); }
	public DialogField getLastNameField() { return getField("last_name"); }
	public DialogContext.DialogFieldState getLastNameFieldState() { return getFieldState("last_name"); }
	public void addLastNameErrorMsg(String msg) { addErrorMessage("last_name", msg); }
	public String getLastName() { return getValue("last_name"); }
	public String getLastName(String defaultValue) { return getValue("last_name", defaultValue); }
	public String getLastNameOrBlank() { return getValue("last_name", ""); }
	public void setLastName(String value) { setValue("last_name", value); }

	public boolean isSsnValueSet() { return hasValue("ssn"); }
	public boolean isSsnFlagSet(long flag) { return flagIsSet("ssn", flag); }
	public void setSsnFlag(long flag) { setFlag("ssn", flag); }
	public void clearSsnFlag(long flag) { clearFlag("ssn", flag); }
	public String getSsnRequestParam() { return request.getParameter("_dc.ssn"); }
	public DialogField getSsnField() { return getField("ssn"); }
	public DialogContext.DialogFieldState getSsnFieldState() { return getFieldState("ssn"); }
	public void addSsnErrorMsg(String msg) { addErrorMessage("ssn", msg); }
	public String getSsn() { return getValue("ssn"); }
	public String getSsn(String defaultValue) { return getValue("ssn", defaultValue); }
	public String getSsnOrBlank() { return getValue("ssn", ""); }
	public void setSsn(String value) { setValue("ssn", value); }

	public boolean isCityValueSet() { return hasValue("city"); }
	public boolean isCityFlagSet(long flag) { return flagIsSet("city", flag); }
	public void setCityFlag(long flag) { setFlag("city", flag); }
	public void clearCityFlag(long flag) { clearFlag("city", flag); }
	public String getCityRequestParam() { return request.getParameter("_dc.city"); }
	public DialogField getCityField() { return getField("city"); }
	public DialogContext.DialogFieldState getCityFieldState() { return getFieldState("city"); }
	public void addCityErrorMsg(String msg) { addErrorMessage("city", msg); }
	public String getCity() { return getValue("city"); }
	public String getCity(String defaultValue) { return getValue("city", defaultValue); }
	public String getCityOrBlank() { return getValue("city", ""); }
	public void setCity(String value) { setValue("city", value); }

	public boolean isStateValueSet() { return hasValue("state"); }
	public boolean isStateFlagSet(long flag) { return flagIsSet("state", flag); }
	public void setStateFlag(long flag) { setFlag("state", flag); }
	public void clearStateFlag(long flag) { clearFlag("state", flag); }
	public String getStateRequestParam() { return request.getParameter("_dc.state"); }
	public DialogField getStateField() { return getField("state"); }
	public DialogContext.DialogFieldState getStateFieldState() { return getFieldState("state"); }
	public void addStateErrorMsg(String msg) { addErrorMessage("state", msg); }
	public String getState() { return getValue("state"); }
	public String getState(String defaultValue) { return getValue("state", defaultValue); }
	public String getStateOrBlank() { return getValue("state", ""); }
	public void setState(String value) { setValue("state", value); }

	public boolean isZipcodeValueSet() { return hasValue("zipcode"); }
	public boolean isZipcodeFlagSet(long flag) { return flagIsSet("zipcode", flag); }
	public void setZipcodeFlag(long flag) { setFlag("zipcode", flag); }
	public void clearZipcodeFlag(long flag) { clearFlag("zipcode", flag); }
	public String getZipcodeRequestParam() { return request.getParameter("_dc.zipcode"); }
	public DialogField getZipcodeField() { return getField("zipcode"); }
	public DialogContext.DialogFieldState getZipcodeFieldState() { return getFieldState("zipcode"); }
	public void addZipcodeErrorMsg(String msg) { addErrorMessage("zipcode", msg); }
	public String getZipcode() { return getValue("zipcode"); }
	public String getZipcode(String defaultValue) { return getValue("zipcode", defaultValue); }
	public String getZipcodeOrBlank() { return getValue("zipcode", ""); }
	public void setZipcode(String value) { setValue("zipcode", value); }

}
