
/* this file is generated by com.netspective.sparx.xaf.form.Dialog.getSubclassedDialogContextCode(), do not modify (you can extend it, though) */

package dialog.context.main;

import com.netspective.sparx.xaf.form.*;

public class PrescriptionEntryContext extends DialogContext
{
	public boolean isPyhsicianNameValueSet() { return hasValue("pyhsician_name"); }
	public boolean isPyhsicianNameFlagSet(long flag) { return flagIsSet("pyhsician_name", flag); }
	public void setPyhsicianNameFlag(long flag) { setFlag("pyhsician_name", flag); }
	public void clearPyhsicianNameFlag(long flag) { clearFlag("pyhsician_name", flag); }
	public String getPyhsicianNameRequestParam() { return request.getParameter("_dc.pyhsician_name"); }
	public DialogField getPyhsicianNameField() { return getField("pyhsician_name"); }
	public DialogContext.DialogFieldState getPyhsicianNameFieldState() { return getFieldState("pyhsician_name"); }
	public void addPyhsicianNameErrorMsg(String msg) { addErrorMessage("pyhsician_name", msg); }
	public String getPyhsicianName() { return getValue("pyhsician_name"); }
	public String getPyhsicianName(String defaultValue) { return getValue("pyhsician_name", defaultValue); }
	public String getPyhsicianNameOrBlank() { return getValue("pyhsician_name", ""); }
	public void setPyhsicianName(String value) { setValue("pyhsician_name", value); }

	public boolean isDeaNumberValueSet() { return hasValue("dea_number"); }
	public boolean isDeaNumberFlagSet(long flag) { return flagIsSet("dea_number", flag); }
	public void setDeaNumberFlag(long flag) { setFlag("dea_number", flag); }
	public void clearDeaNumberFlag(long flag) { clearFlag("dea_number", flag); }
	public String getDeaNumberRequestParam() { return request.getParameter("_dc.dea_number"); }
	public DialogField getDeaNumberField() { return getField("dea_number"); }
	public DialogContext.DialogFieldState getDeaNumberFieldState() { return getFieldState("dea_number"); }
	public void addDeaNumberErrorMsg(String msg) { addErrorMessage("dea_number", msg); }
	public String getDeaNumber() { return getValue("dea_number"); }
	public String getDeaNumber(String defaultValue) { return getValue("dea_number", defaultValue); }
	public String getDeaNumberOrBlank() { return getValue("dea_number", ""); }
	public void setDeaNumber(String value) { setValue("dea_number", value); }

	public boolean isPiValueSet() { return hasValue("pi"); }
	public boolean isPiFlagSet(long flag) { return flagIsSet("pi", flag); }
	public void setPiFlag(long flag) { setFlag("pi", flag); }
	public void clearPiFlag(long flag) { clearFlag("pi", flag); }
	public String getPiRequestParam() { return request.getParameter("_dc.pi"); }
	public DialogField getPiField() { return getField("pi"); }
	public DialogContext.DialogFieldState getPiFieldState() { return getFieldState("pi"); }
	public void addPiErrorMsg(String msg) { addErrorMessage("pi", msg); }
	public String getPi() { return getValue("pi"); }
	public String getPi(String defaultValue) { return getValue("pi", defaultValue); }
	public String getPiOrBlank() { return getValue("pi", ""); }
	public void setPi(String value) { setValue("pi", value); }

	public boolean isFirstNameValueSet() { return hasValue("first_name"); }
	public boolean isFirstNameFlagSet(long flag) { return flagIsSet("first_name", flag); }
	public void setFirstNameFlag(long flag) { setFlag("first_name", flag); }
	public void clearFirstNameFlag(long flag) { clearFlag("first_name", flag); }
	public String getFirstNameRequestParam() { return request.getParameter("_dc.first_name"); }
	public DialogField getFirstNameField() { return getField("first_name"); }
	public DialogContext.DialogFieldState getFirstNameFieldState() { return getFieldState("first_name"); }
	public void addFirstNameErrorMsg(String msg) { addErrorMessage("first_name", msg); }
	public String getFirstName() { return getValue("first_name"); }
	public String getFirstName(String defaultValue) { return getValue("first_name", defaultValue); }
	public String getFirstNameOrBlank() { return getValue("first_name", ""); }
	public void setFirstName(String value) { setValue("first_name", value); }

	public boolean isLastNameValueSet() { return hasValue("last_name"); }
	public boolean isLastNameFlagSet(long flag) { return flagIsSet("last_name", flag); }
	public void setLastNameFlag(long flag) { setFlag("last_name", flag); }
	public void clearLastNameFlag(long flag) { clearFlag("last_name", flag); }
	public String getLastNameRequestParam() { return request.getParameter("_dc.last_name"); }
	public DialogField getLastNameField() { return getField("last_name"); }
	public DialogContext.DialogFieldState getLastNameFieldState() { return getFieldState("last_name"); }
	public void addLastNameErrorMsg(String msg) { addErrorMessage("last_name", msg); }
	public String getLastName() { return getValue("last_name"); }
	public String getLastName(String defaultValue) { return getValue("last_name", defaultValue); }
	public String getLastNameOrBlank() { return getValue("last_name", ""); }
	public void setLastName(String value) { setValue("last_name", value); }

	public boolean isSsnValueSet() { return hasValue("ssn"); }
	public boolean isSsnFlagSet(long flag) { return flagIsSet("ssn", flag); }
	public void setSsnFlag(long flag) { setFlag("ssn", flag); }
	public void clearSsnFlag(long flag) { clearFlag("ssn", flag); }
	public String getSsnRequestParam() { return request.getParameter("_dc.ssn"); }
	public DialogField getSsnField() { return getField("ssn"); }
	public DialogContext.DialogFieldState getSsnFieldState() { return getFieldState("ssn"); }
	public void addSsnErrorMsg(String msg) { addErrorMessage("ssn", msg); }
	public String getSsn() { return getValue("ssn"); }
	public String getSsn(String defaultValue) { return getValue("ssn", defaultValue); }
	public String getSsnOrBlank() { return getValue("ssn", ""); }
	public void setSsn(String value) { setValue("ssn", value); }

	public boolean isCityValueSet() { return hasValue("city"); }
	public boolean isCityFlagSet(long flag) { return flagIsSet("city", flag); }
	public void setCityFlag(long flag) { setFlag("city", flag); }
	public void clearCityFlag(long flag) { clearFlag("city", flag); }
	public String getCityRequestParam() { return request.getParameter("_dc.city"); }
	public DialogField getCityField() { return getField("city"); }
	public DialogContext.DialogFieldState getCityFieldState() { return getFieldState("city"); }
	public void addCityErrorMsg(String msg) { addErrorMessage("city", msg); }
	public String getCity() { return getValue("city"); }
	public String getCity(String defaultValue) { return getValue("city", defaultValue); }
	public String getCityOrBlank() { return getValue("city", ""); }
	public void setCity(String value) { setValue("city", value); }

	public boolean isStateValueSet() { return hasValue("state"); }
	public boolean isStateFlagSet(long flag) { return flagIsSet("state", flag); }
	public void setStateFlag(long flag) { setFlag("state", flag); }
	public void clearStateFlag(long flag) { clearFlag("state", flag); }
	public String getStateRequestParam() { return request.getParameter("_dc.state"); }
	public DialogField getStateField() { return getField("state"); }
	public DialogContext.DialogFieldState getStateFieldState() { return getFieldState("state"); }
	public void addStateErrorMsg(String msg) { addErrorMessage("state", msg); }
	public String getState() { return getValue("state"); }
	public String getState(String defaultValue) { return getValue("state", defaultValue); }
	public String getStateOrBlank() { return getValue("state", ""); }
	public void setState(String value) { setValue("state", value); }

	public boolean isZipValueSet() { return hasValue("zip"); }
	public boolean isZipFlagSet(long flag) { return flagIsSet("zip", flag); }
	public void setZipFlag(long flag) { setFlag("zip", flag); }
	public void clearZipFlag(long flag) { clearFlag("zip", flag); }
	public String getZipRequestParam() { return request.getParameter("_dc.zip"); }
	public DialogField getZipField() { return getField("zip"); }
	public DialogContext.DialogFieldState getZipFieldState() { return getFieldState("zip"); }
	public void addZipErrorMsg(String msg) { addErrorMessage("zip", msg); }
	public String getZip() { return getValue("zip"); }
	public String getZip(String defaultValue) { return getValue("zip", defaultValue); }
	public String getZipOrBlank() { return getValue("zip", ""); }
	public void setZip(String value) { setValue("zip", value); }

	public boolean isPi2ValueSet() { return hasValue("pi2"); }
	public boolean isPi2FlagSet(long flag) { return flagIsSet("pi2", flag); }
	public void setPi2Flag(long flag) { setFlag("pi2", flag); }
	public void clearPi2Flag(long flag) { clearFlag("pi2", flag); }
	public String getPi2RequestParam() { return request.getParameter("_dc.pi2"); }
	public DialogField getPi2Field() { return getField("pi2"); }
	public DialogContext.DialogFieldState getPi2FieldState() { return getFieldState("pi2"); }
	public void addPi2ErrorMsg(String msg) { addErrorMessage("pi2", msg); }
	public String getPi2() { return getValue("pi2"); }
	public String getPi2(String defaultValue) { return getValue("pi2", defaultValue); }
	public String getPi2OrBlank() { return getValue("pi2", ""); }
	public void setPi2(String value) { setValue("pi2", value); }

	public boolean isDrugValueSet() { return hasValue("drug"); }
	public boolean isDrugFlagSet(long flag) { return flagIsSet("drug", flag); }
	public void setDrugFlag(long flag) { setFlag("drug", flag); }
	public void clearDrugFlag(long flag) { clearFlag("drug", flag); }
	public String getDrugRequestParam() { return request.getParameter("_dc.drug"); }
	public DialogField getDrugField() { return getField("drug"); }
	public DialogContext.DialogFieldState getDrugFieldState() { return getFieldState("drug"); }
	public void addDrugErrorMsg(String msg) { addErrorMessage("drug", msg); }
	public String getDrug() { return getValue("drug"); }
	public String getDrug(String defaultValue) { return getValue("drug", defaultValue); }
	public String getDrugOrBlank() { return getValue("drug", ""); }
	public void setDrug(String value) { setValue("drug", value); }

	public boolean isDosageValueSet() { return hasValue("dosage"); }
	public boolean isDosageFlagSet(long flag) { return flagIsSet("dosage", flag); }
	public void setDosageFlag(long flag) { setFlag("dosage", flag); }
	public void clearDosageFlag(long flag) { clearFlag("dosage", flag); }
	public String getDosageRequestParam() { return request.getParameter("_dc.dosage"); }
	public DialogField getDosageField() { return getField("dosage"); }
	public DialogContext.DialogFieldState getDosageFieldState() { return getFieldState("dosage"); }
	public void addDosageErrorMsg(String msg) { addErrorMessage("dosage", msg); }
	public String getDosage() { return getValue("dosage"); }
	public String getDosage(String defaultValue) { return getValue("dosage", defaultValue); }
	public String getDosageOrBlank() { return getValue("dosage", ""); }
	public void setDosage(String value) { setValue("dosage", value); }

	public boolean isQuantityValueSet() { return hasValue("quantity"); }
	public boolean isQuantityFlagSet(long flag) { return flagIsSet("quantity", flag); }
	public void setQuantityFlag(long flag) { setFlag("quantity", flag); }
	public void clearQuantityFlag(long flag) { clearFlag("quantity", flag); }
	public String getQuantityRequestParam() { return request.getParameter("_dc.quantity"); }
	public DialogField getQuantityField() { return getField("quantity"); }
	public DialogContext.DialogFieldState getQuantityFieldState() { return getFieldState("quantity"); }
	public void addQuantityErrorMsg(String msg) { addErrorMessage("quantity", msg); }
	public String getQuantity() { return getValue("quantity"); }
	public String getQuantity(String defaultValue) { return getValue("quantity", defaultValue); }
	public String getQuantityOrBlank() { return getValue("quantity", ""); }
	public void setQuantity(String value) { setValue("quantity", value); }

	public boolean isInstructionsValueSet() { return hasValue("instructions"); }
	public boolean isInstructionsFlagSet(long flag) { return flagIsSet("instructions", flag); }
	public void setInstructionsFlag(long flag) { setFlag("instructions", flag); }
	public void clearInstructionsFlag(long flag) { clearFlag("instructions", flag); }
	public String getInstructionsRequestParam() { return request.getParameter("_dc.instructions"); }
	public DialogField getInstructionsField() { return getField("instructions"); }
	public DialogContext.DialogFieldState getInstructionsFieldState() { return getFieldState("instructions"); }
	public void addInstructionsErrorMsg(String msg) { addErrorMessage("instructions", msg); }
	public String getInstructions() { return getValue("instructions"); }
	public String getInstructions(String defaultValue) { return getValue("instructions", defaultValue); }
	public String getInstructionsOrBlank() { return getValue("instructions", ""); }
	public void setInstructions(String value) { setValue("instructions", value); }

}
