
/* this file is generated by com.netspective.sparx.util.xml.XmlSource.createNodeIdentifiersClass(), do not modify (you can extend it, though) */

package id.config.sparx.shared.dialog.field;

public class Calendar
{
    static public final String IMAGE_URL = "sparx.shared.dialog.field.calendar.image-url";
    static public final String JS_SRC = "sparx.shared.dialog.field.calendar.js-src";
}
