
/* this file is generated by com.netspective.sparx.util.xml.XmlSource.createNodeIdentifiersClass(), do not modify (you can extend it, though) */

package id.config.sparx.ace;

public class Login
{
    static public final String DIALOG_CLASS = "sparx.ace.login.dialog-class";
    static public final String USER_NAME = "sparx.ace.login.user-name";
    static public final String USER_PASSWORD = "sparx.ace.login.user-password";
}
