
/* this file is generated by com.netspective.sparx.util.xml.XmlSource.createNodeIdentifiersClass(), do not modify (you can extend it, though) */

package id.config.sparx.ace;

public class Monitor
{
    static public final String LOGS = "sparx.ace.monitor.logs";
}
