
/* this file is generated by com.netspective.sparx.util.xml.XmlSource.createNodeIdentifiersClass(), do not modify (you can extend it, though) */

package id.config.sparx.shared.dialog;

public class Field
{
    static public final String POPUP_IMAGE_SRC = "sparx.shared.dialog.field.popup-image-src";
}
