
/* this file is generated by com.netspective.sparx.util.xml.XmlSource.createNodeIdentifiersClass(), do not modify (you can extend it, though) */

package id.config.sparx;

public class Ace
{
    static public final String ACL_BROWSER_XSL = "sparx.ace.acl-browser-xsl";
    static public final String BOOKMARKS = "sparx.ace.bookmarks";
    static public final String CONFIG_BROWSER_XSL = "sparx.ace.config-browser-xsl";
    static public final String DOCS_BROWSER_XSL = "sparx.ace.docs-browser-xsl";
    static public final String IMAGES_ROOT_URL = "sparx.ace.images-root-url";
    static public final String METRICS_BROWSER_XSL = "sparx.ace.metrics-browser-xsl";
    static public final String PROPERTIES_BROWSER_XSL = "sparx.ace.properties-browser-xsl";
    static public final String QUERY_DEFN_BROWSER_XSL = "sparx.ace.query-defn-browser-xsl";
    static public final String ROOT_URL = "sparx.ace.root-url";
    static public final String SCHEMA_BROWSER_XSL = "sparx.ace.schema-browser-xsl";
    static public final String SQL_BROWSER_XSL = "sparx.ace.sql-browser-xsl";
    static public final String TRANSFORM = "sparx.ace.transform";
    static public final String UI_BROWSER_XSL = "sparx.ace.ui-browser-xsl";
    static public final String XSLT_PATH = "sparx.ace.xslt-path";
    static public final String XSLT_URL = "sparx.ace.xslt-url";
}
