
/* this file is generated by com.netspective.sparx.util.xml.XmlSource.createNodeIdentifiersClass(), do not modify (you can extend it, though) */

package id.config.sparx;

public class Shared
{
    static public final String CSS_PATH = "sparx.shared.css-path";
    static public final String CSS_URL = "sparx.shared.css-url";
    static public final String IMAGES_PATH = "sparx.shared.images-path";
    static public final String IMAGES_URL = "sparx.shared.images-url";
    static public final String RESOURCES_PATH = "sparx.shared.resources-path";
    static public final String RESOURCES_URL = "sparx.shared.resources-url";
    static public final String ROOT_PATH = "sparx.shared.root-path";
    static public final String ROOT_URL = "sparx.shared.root-url";
    static public final String SCRIPTS_PATH = "sparx.shared.scripts-path";
    static public final String SCRIPTS_URL = "sparx.shared.scripts-url";
    static public final String XSLT_PATH = "sparx.shared.xslt-path";
    static public final String XSLT_URL = "sparx.shared.xslt-url";
}
