
/* this file is generated by com.netspective.sparx.util.xml.XmlSource.createNodeIdentifiersClass(), do not modify (you can extend it, though) */

package id.dialog;

public class Gift
{
    static public final String DETAILGIFT = "Gift.DetailGift";
    static public final String NEWGIFT = "Gift.NewGift";
    static public final String SUGGESTION = "Gift.Suggestion";
    static public final String YOURGIFTLIST = "Gift.YourGiftList";
}
