
/* this file is generated by com.netspective.sparx.util.xml.XmlSource.createNodeIdentifiersClass(), do not modify (you can extend it, though) */

package id.dialog;

public class User
{
    static public final String NEWUSERREGISTRATION = "User.NewUserRegistration";
    static public final String USEREDIT = "User.UserEdit";
}
